### ISSUE TITLE
Chia sẻ, cập nhật thông tin giữa các đội, TNV khi có trường hợp cần ứng cứu thêm vào dữ liệu.

### ISSUE THREAD

**Issue by juno249** [Cuuhomientrung/cuuhomientrung#100]
1. Trường hợp khi có một hộ dân cần ứng cứu thêm vào dữ liệu thì cần có sự cập nhật nhanh chóng cho các đội đang hoạt động nắm sớm nhất tin tức.

2. Kiểm tra những hộ dân cần ứng cứu thêm vào mà sau một thời gian dài mà vẫn chưa có đội tiếp nhận thì cập nhật cho các TNV kết nối liên lạc cập nhật tin tức để có phương pháp hoặc liên hệ với các đội gần nhất để kịp thời ứng cứu.

3. Các đội nên có một kênh thông tin chung  ngoài điện thoại như Zalo, Facebook, Telegram,... để hệ thống dễ dàng tiếp cận và cập nhật thông tin liên tục dễ dàng đến toàn thành viên của đội. (Dùng chatbot)

**Comment by kc97ble** [comment]
Duyệt.

Mình cho rằng đây là một tính năng cần thiết, có thể giúp ích nhiều cho đội cứu hộ.
Rất mong nhận được sự tư vấn về giải pháp của mọi người. @hailoc12

**Comment by kc97ble** [comment]
Mình đã gắn nhãn `out of gen2 scope`.

Tham khảo: [Định hướng của Gen-2](https://docs.google.com/document/d/1InhG0Pd2Bpt-lY7rZAc7TyznlWhOxNCocRpVSFX720Y/edit?usp=sharing)
