### ISSUE TITLE
Thêm lịch sử liên hệ

### ISSUE THREAD

**Issue by thuyvan-kieu** [Cuuhomientrung/cuuhomientrung#103]
Các tình nguyện viên liên lạc với các hộ dân nhiều lần. Cần có một trường lịch sử liên hệ để các tnv có thể note được ai là người liên hệ, giờ liên hệ và kết quả liên hệ

**Comment by dothanhlam97** [comment]
@thuyvan-kieu thuy
chị ơi mình viết thêm phần description cho mấy bạn dev dễ làm 
mà a @DungDA hình như có làm rồi nhỉ

**Comment by thaidn** [comment]
+1

Tôi nghĩ phần ghi chú nên hoạt động giống như comment của GitHub. Mỗi ghi chú mới sẽ được đưa vào thành một comment, sắp xếp theo thứ tự thời gian để tiện theo dõi.

Nếu chưa có ai làm phần này thì cuối tuần này tôi sẽ thử.

**Comment by dothanhlam97** [comment]
Sorry mọi người vì phần description đã làm nhiều bạn hiểu sai task:

Context: Khi tnv gọi cho các hộ dân để kết nối việc cứu hộ, thường bị không liên lạc được. Nhưng 1 hộ dân ko được xử lý bởi duy nhất 1 tnv mà rất nhiều tnv cho nên bạn sau không biết đã có ai gọi chưa và gọi vào lúc nào.

Cách làm hiện tại: Các tnv đang note vào trường Note (Đã gọi nhưng k liên lạc được lúc ... giờ).

Expect: 
Technical side: Có thêm 1 trường history để lưu lại lịch sử cuộc gọi.
UI: 
- TNV sau khi gọi điện sẽ có một dropdown list kiểu (Ko gọi đc, đã kết nối, abc xyz). Bên mình sẽ tự cập nhật vào History là Ko gọi đc vào lúc ... (lấy update time). 
- Trong table ở trang hộ dân, khi ấn vào xem lịch sử sẽ hiển thị 1 dialog thể hiện:
*<Trạng thái cuộc gọi> vào lúc <> giờ 

Ví dụ: 
Không liên lạc được lúc 8:10
Không liên lạc được lúc 11:15
Đã liên lạc được lúc lúc 15:00

cc: @kc97ble Giải đáp thắc mắc của Kiên

**Comment by kc97ble** [comment]
Tạm thời bỏ qua.

Mình thấy ý tưởng này có giá trị, song giá trị không nhiều, cách giải quyết tạm thời vẫn dùng được.
