### ISSUE TITLE
Trong mục thêm mới hộ dân, phần chọn xã, sau khi chọn xong tỉnh, huyện nhưng vẫn không có data của xã

### ISSUE THREAD

**Issue by crazywolfxju** [Cuuhomientrung/cuuhomientrung#108]
![8](https://user-images.githubusercontent.com/12232365/97075807-6a1b4700-161c-11eb-8592-45c3eec14912.png)

**Comment by dungpt3003** [comment]
@crazywolfxju bạn chọn tỉnh và huyện nào vậy?

**Comment by dothanhlam97** [comment]
@dungpt3003 check ddc chua Dung oi

**Comment by crazywolfxju** [comment]
Em vừa check lại ạ. Cái này do data ạ.

**Comment by dothanhlam97** [comment]
Vậy mình close nhé. Thanks @crazywolfxju  đã confirm

**Comment by crazywolfxju** [comment]
Dạ vâng ạ,
