### ISSUE TITLE
Mục [thêm đôi cứu hộ], bị lỗi khi thêm edit xã

### ISSUE THREAD

**Issue by crazywolfxju** [Cuuhomientrung/cuuhomientrung#110]
Mục xã,
Trường hợp thử thêm mới thì được, nhưng nếu click vào edit thì sẽ ra popup với nội dung là website như bên mục thêm hộ dân đã nêu trên.
![image](https://user-images.githubusercontent.com/12232365/97083514-99957800-164b-11eb-8809-e478ddee9e10.png)

**Comment by dungpt3003** [comment]
Đã reproduce được lỗi, sẽ fix sớm ạ.

**Comment by crazywolfxju** [comment]
Mục edit xã trong [THÊM MỚI HỘ DÂN] cũng đang có lỗi tương tự ạ

**Comment by crazywolfxju** [comment]
Hiện tai các mục này đang không còn cho phép thêm mới hay chỉnh sửa nữa
![Uploading 21.png…]()
