### ISSUE TITLE
Mục [thống kê xã] hiện đang không search được thông tin

### ISSUE THREAD

**Issue by crazywolfxju** [Cuuhomientrung/cuuhomientrung#111]
![image](https://user-images.githubusercontent.com/12232365/97083621-2fc99e00-164c-11eb-8d2e-42b31a59ad4a.png)

**Comment by dothanhlam97** [comment]
Không search được gì vậy bạn

**Comment by crazywolfxju** [comment]
này em đang không thấy kết quả nào ạ, e có test mấy huyện nhưng đều không có thông tin về xã ạ
![16](https://user-images.githubusercontent.com/12232365/97097486-4277bd80-16b4-11eb-99fb-eed85cb34345.png)

**Comment by dothanhlam97** [comment]
@crazywolfxju mình nghĩ do huyện đó không có xã / hộ dân nào thôi. Mình kiểm tra Lệ Thuỷ vẫn có

**Comment by crazywolfxju** [comment]
Dạ để rồi em check lại cái này ạ. Hiện tại staging em đang k vào được ạ

**Comment by crazywolfxju** [comment]
Em đã kiểm tra lại và thấy có huyện có huyện không ạ. Nhưng mà Lệ Thủy vẫn không có data thật ạ. Em có check trong danh sách hộ cần ứng cứu thì Lệ thủy vẫn có danh sách ứng cứu ạ
Trong hình search Tuyên Hóa là có danh sách xã, Lệ Thủy không có ạ
![image](https://user-images.githubusercontent.com/12232365/97099471-cd64b200-16cc-11eb-872d-ae066d9a1ed9.png)
![17](https://user-images.githubusercontent.com/12232365/97099472-d190cf80-16cc-11eb-9781-d528f1776eb7.png)


![image](https://user-images.githubusercontent.com/12232365/97099456-9abab980-16cc-11eb-8aee-a0b2c9c77eba.png)

**Comment by bangnbx** [comment]
Mình có kiểm tra thì thấy có 2 huyện Lệ Thuỷ (LT1), huyện còn lại tên là Lệ Thủy (LT2) (thanh hỏi ở chữ u).
LT2 chính là cái mà @crazywolfxju bảo ở trên, thời điểm mình kiểm tra 22h50 25/10/2020 thì thấy đã có một số record tuy nhiên vẫn ít, phần lớn data nằm ở LT1.

@dungpt3003  Vấn đề này sau khi chuẩn hoá được DB thì sẽ không còn nữa. Tuy nhiên có thể thấy một vấn đề ở đây là hai người sử dụng cách bỏ dấu tiếng Việt khác nhau -> kết quả search khác nhau. Chắc sau cần phải chuẩn hoá trước khi đưa vào search, bỏ hết accent đưa về không dấu chẳng hạn?

<img width="1026" alt="Screen Shot 2020-10-25 at 22 48 53" src="https://user-images.githubusercontent.com/13524874/97111986-65d25500-1714-11eb-91bf-9c7e909087cf.png">

**Comment by dungpt3003** [comment]
Okay vậy có 2 vấn đề:
- Chuẩn hoá lại data về location (đã có issue)
- Xử lý query string (có dấu, không dấu)

**Comment by bangnbx** [comment]
Vấn đề thứ 2: https://github.com/Cuuhomientrung/cuuhomientrung/issues/125

**Comment by freeloneman** [comment]
Vấn đề thứ 1: #80
