### ISSUE TITLE
Bộ lọc "Bởi trạng thái"ở trang thông tin Hộ Dân cần đưa về dropdown

### ISSUE THREAD

**Issue by crazywolfxju** [Cuuhomientrung/cuuhomientrung#112]
![11](https://user-images.githubusercontent.com/12232365/97083643-69020e00-164c-11eb-8759-03990927b4b9.png)

**Comment by dothanhlam97** [comment]
@DungDA  @dungpt3003

**Comment by dungpt3003** [comment]
Mình vừa check thấy filter bình thường mà, bạn @crazywolfxju cho mình screenshot phần kết quả luôn được không?

**Comment by crazywolfxju** [comment]
ah cái này không phải lỗi filter mà là mong muốn là để tất các options này vào môt drop down list để cái giao diện nó gọn gàng hơn ạ.
