### ISSUE TITLE
Mục [Thêm hộ dân cần cứu] Phần thêm mới trạng thái bị lỗi

### ISSUE THREAD

**Issue by crazywolfxju** [Cuuhomientrung/cuuhomientrung#113]
![7](https://user-images.githubusercontent.com/12232365/97083958-93ed6180-164e-11eb-9506-1e60b029066f.png)
![image](https://user-images.githubusercontent.com/12232365/97083963-9ea7f680-164e-11eb-951f-9b69ec2694be.png)

**Comment by dothanhlam97** [comment]
Đã disable tính năng thêm trạng thái.
