### ISSUE TITLE
Bô lọc [Bởi tỉnh] Trong thống kê xã, đưa về dropdown

### ISSUE THREAD

**Issue by crazywolfxju** [Cuuhomientrung/cuuhomientrung#120]
![18](https://user-images.githubusercontent.com/12232365/97099519-3e0bce80-16cd-11eb-929a-8fa75abf7998.png)

**Comment by dothanhlam97** [comment]
Fixed by https://github.com/Cuuhomientrung/cuuhomientrung/pull/119
