### ISSUE TITLE
Giải quyết vấn đề một hộ dân bị nhập nhiều lần

### ISSUE THREAD

**Issue by dothanhlam97** [Cuuhomientrung/cuuhomientrung#121]
Nếu đã có số đt đó rồi thì mình sẽ hiện box & hiển thị trường trùng lặp ra, hỏi có muốn thêm không. 
Sau này mình có muốn validation trường khác thì cũng theo cơ chế tương tự chứ không phải code riêng cho từng fields

**Comment by kc97ble** [comment]
nên tạo một cái view để nhập dữ liệu

**Comment by kc97ble** [comment]
Sẽ xem xét lại issue này sau khi issue https://github.com/Cuuhomientrung/cuuhomientrung/issues/208 được xử lý.

**Comment by kc97ble** [comment]
Đóng.

Vui lòng thảo luận tại issue #208
