### ISSUE TITLE
Môi trường Production, Cho phép nhập tên để tìm tỉnh/huyện/xã dễ dàng hơn

### ISSUE THREAD

**Issue by crazywolfxju** [Cuuhomientrung/cuuhomientrung#132]
Trong mục [Hộ dân cần ứng cứu] => [Thêm 1. Hộ dân cần ứng cứu] => Mục chọn Tỉnh huyện xã như hình hiện không cho nhập tên để tìm tên tỉnh, huyện, xã. Khi số lượng nhiều mà tìm bằng mắt thì khá khó khăn và mất thời gian. Ngoài ra, một ý nhỏ là tăng width của tỉnh, huyện xã một chút, để tránh trường hợp bị che như hình (Note: Vấn đề chung cho 3 trường tỉnh,huyện, xã nhưng hình chỉ chụp mỗi của tỉnh để minh họa.)
![Screenshot (42)](https://user-images.githubusercontent.com/12232365/97124888-46b7df80-1775-11eb-8e10-beafce07b011.png)

**Comment by crazywolfxju** [comment]
Vấn đề tương tự trong mục [THÊM ĐỘI CỨU HỘ]
![Screenshot (43)](https://user-images.githubusercontent.com/12232365/97125582-bb8c1900-1777-11eb-8695-b34bae4d3994.png)

**Comment by vu-luong** [comment]
Mình nhận làm issue này nhé!

**Comment by dothanhlam97** [comment]
Cảm ơn @vu-luong
