### ISSUE TITLE
[DevOps][Homepage] Tạo link redirect tới trang dashboard & Hiển thị link ra ngoài trang homepage 

### ISSUE THREAD

**Issue by hailoc12** [Cuuhomientrung/cuuhomientrung#134]
Mô tả: 
- Tạo link cuuhomientrung.info/dashboard trỏ tới https://datastudio.google.com/reporting/e48d25ad-3e88-4f3c-8e60-e5a18947cd3a/page/kBKlB

**Comment by DungDA** [comment]
Done https://cuuhomientrung.info/dashboard/
