### ISSUE TITLE
Môi trường [Production] , vấn đề giao diện, trang [Hộ dân cần ứng cứu]

### ISSUE THREAD

**Issue by crazywolfxju** [Cuuhomientrung/cuuhomientrung#135]
1) Đề xuất thay [Thêm 1. Hộ dân cần ứng cứu + ] thành [Thêm hộ dân cần ứng cứu +]
2) Thay màu nền của button thành màu xanh như mô tả trong nhình 
![20](https://user-images.githubusercontent.com/12232365/97148421-77683b00-17ae-11eb-91f3-f147b39524a9.png)

**Comment by crazywolfxju** [comment]
Trang [Các đội cứu hộ] cũng đề xuất những vấn đề như trên
1) Đề xuất thay [Thêm 2. Các đội Cứu hộ + ] bằng [Thê đội cứu hộ + ]
2) Thay màu nền của button thành màu xanh
![Screenshot (44)](https://user-images.githubusercontent.com/12232365/97148704-ec3b7500-17ae-11eb-8e39-345b2f8256bf.png)

**Comment by vu-luong** [comment]
Mình đã sửa lại như đề xuất ở PR https://github.com/Cuuhomientrung/cuuhomientrung/pull/186

![image](https://user-images.githubusercontent.com/8142030/97761647-fadcb000-1b51-11eb-9a70-7e7c42712473.png)
