### ISSUE TITLE
[Chưa chốt] Cập nhật lại trạng thái

### ISSUE THREAD

**Issue by dothanhlam97** [Cuuhomientrung/cuuhomientrung#144]
Chỉ tiêu cho các trạng thái:
1.	Chưa xác minh: TNV chưa liên hệ; đã liên hệ nhưng trong hoàn cảnh cần kiểm tra lại sau 1 vài ngày (ghi rõ trong ghi chú)
2.	Không gọi được: Gọi không nghe máy; gọi không liên lạc được; nhầm số máy; số điện thoại không đúng
3.	Cần ứng cứu gấp: chưa có gì ăn uống 4 -5 ngày trở lên; tính mạng nguy kịch, ốm sốt, bệnh tật cần thuốc men, cấp cứu, sinh đẻ…
4.	Đã gửi cứu hộ: (dành cho team kết nối)
5.	Cần ngay nhu yếu phẩm (thay cho Cần thức ăn): hiện tại chưa có gì, nhu cầu tiếp trợ đồ ăn, gạo, muối, xoong nồi….; và/hoặc chăn màn, quần áo...;
6.	Cần hỗ trợ thêm (thay cho Cần thuốc men): đã có đoàn tiếp trợ nhưng vẫn cần đồ ăn, gạo, muối, xoong nồi, và/hoặc chăn màn, quần áo...;
7.	Không cần hỗ trợ (thay cho Đã an toàn): đã được các đoàn cứu trợ, trong 4-5 ngày tới không cần cứu trợ tiếp, để nhường cho các trường hợp khác
8.	Cần hỗ trợ ngay (thêm mới): xập, trôi mất toàn bộ nhà
9.	Học đường (thêm mới): nhu cầu sách vở, đồ dùng học tập, bàn ghế, tiền mua lại thiết bị học tập.
Nếu được thống nhất thì sau khi dev điều chỉnh trạng thái sẽ thống nhất giữa team xác nhận thông tin với team kết nối để 2 team cùng hiểu các trạng thái mình cập nhật lên, kết nối giữa các đội cứu hộ và dân thiết thực hơn.

**Comment by freeloneman** [comment]
Có khả năng trùng với #141

**Comment by dothanhlam97** [comment]
@hailoc12 cái này còn làm ko a ơi ?
