### ISSUE TITLE
Home page - New UI

### ISSUE THREAD

**Issue by dothanhlam97** [Cuuhomientrung/cuuhomientrung#145]
Designer: @kc97ble 
![image](https://user-images.githubusercontent.com/17758870/97228002-32ec9780-17ce-11eb-932b-7b9725420b9b.png)

**Comment by kc97ble** [comment]
https://www.figma.com/file/IQpYhb51qexwLHMyoDQxr1/cuuhomientrung.info?node-id=57%3A90
