### ISSUE TITLE
[UX] Hiển thị những tỉnh có số hộ dân cần cứu hộ cao nhất trong 24h trở lại 

### ISSUE THREAD

**Issue by hailoc12** [Cuuhomientrung/cuuhomientrung#155]
Mô tả: 
- Danh sách nhựng tỉnh hiện ở ngoài homepage đang sort theo tổng số hộ dân ---> Những tỉnh từ cơn bão số 7 vẫn được ưu tiên hiện 
![image](https://user-images.githubusercontent.com/288295/97335408-67388480-18b0-11eb-9907-d857d56e2c0c.pn

Yêu cầu: 
- Hiển thị ra homepage những tỉnh cố số hộ dân cao nhất trong 24h trở lại (số liệu về tổng số hộ / tổng số đội cứu hộ thì vẫn giữ nguyên)

**Comment by dothanhlam97** [comment]
https://github.com/Cuuhomientrung/cuuhomientrung/pull/156
