### ISSUE TITLE
Môi trường [Production] Thêm dropdown cho bộ lọc [bởi tình trạng] trong trang [Tình nguyện viên thông tin]

### ISSUE THREAD

**Issue by crazywolfxju** [Cuuhomientrung/cuuhomientrung#165]
Có 2 chỉnh sử cho trang này:
1) Thêm dropdown cho mục [Bởi tình trạng]
2) Đề xuất thay đổi một số chỉ mục như trong hình
                          [Bởi tình trạng]] sửa thành [Chọn tình trạng]
                          [Bộ lọc theo tỉnh] ==>  [Chọn tỉnh],  
                          [Bởi Lọc theo huyện] ===> [Chọn huyện]
                          [Bởi Lọc theo xã] ===> [Chọn xã]

![24](https://user-images.githubusercontent.com/12232365/97545708-b85e8a80-1a0e-11eb-89fb-7d8f6cbc3d38.png)

**Comment by crazywolfxju** [comment]
Đề xuất thay đổi một số chỉ mục như trong hình tương tự với bộ lọc trong trang đội cứu hộ và hộ dân cần ứng cứu.

**Comment by thaidn** [comment]
Nếu chưa có ai xử lý chỗ này, tôi sẽ làm nhé.

**Comment by thaidn** [comment]
>Đề xuất thay đổi một số chỉ mục như trong hình
[Bởi tình trạng]] sửa thành [Chọn tình trạng]
[Bộ lọc theo tỉnh] ==> [Chọn tỉnh],
[Bởi Lọc theo huyện] ===> [Chọn huyện]
[Bởi Lọc theo xã] ===> [Chọn xã]

Có vẻ như chữ `Bởi` là do Django dịch ra từ chữ `By`. Có cách nào sửa lại thành `Chọn`, nhưng khá phức tạp: https://stackoverflow.com/questions/7878028/override-default-django-translations. Nếu mọi người đồng ý thì tôi sẽ làm thử.

Có thể sửa `Bộ lọc theo tỉnh` thành `Bởi tỉnh`. Cái này thì dễ hơn, nếu mọi người đồng ý tôi sẽ làm cái này trước.
