### ISSUE TITLE
Liên lạc với đội phát triển

### ISSUE THREAD

**Issue by thaidn** [Cuuhomientrung/cuuhomientrung#175]
Rất cảm ơn đội phát triển đã làm dự án này.

Trên README có ghi

>Nếu là senior, bạn có thể ứng cử làm manager cho dự án này để tiếp tục hoàn thiện dự án phục vụ cộng đồng

Tôi có chút kinh nghiệm quản lý, nếu đội phát triển vẫn cần người thì tôi có thể giúp được chút ít. Không biết làm sao để liên lạc với các bạn? Email của tôi là thaidn@gmail.com.

Ngoài ra:

- Tôi có thể tài trợ computing resources để chạy dự án này.
- Tôi cũng có biết chút ít về security, không biết có cần thiết hay không, nhưng nếu các bạn cần tư vấn thì tôi cũng có thể giúp.

**Comment by dothanhlam97** [comment]
Cảm ơn anh đã interested in vào dự án.
Em add anh vào slack bằng email thaidn@gmail.com nhé.

**Comment by freeloneman** [comment]
@thaidn nếu vẫn chưa được thì bạn check mail mình vừa gửi cho bạn. Thanks

**Comment by thaidn** [comment]
Tôi đã vào được rồi, xin cảm ơn.
