### ISSUE TITLE
[Hỗ trợ] Phát triển client cho thiết bị di động

### ISSUE THREAD

**Issue by thuongleit** [Cuuhomientrung/cuuhomientrung#177]
Mình thấy dự án này rất ý nghĩa và thiết thực. Rất cảm ơn nhóm đã phát triển dự án này. 

Mình có kinh nghiệm về lập trình native mobile và Flutter. Mình rất muốn tham gia đóng góp vào dự án này bằng cách hỗ trợ xây dựng mobile client. Ứng dụng sẽ được viết bằng Flutter và build theo bloc architecture, và hỗ trợ build app cả Android và iOS. Không biết ý kiến của nhóm thế nào? Mình cảm ơn mọi người!

**Comment by thuongleit** [comment]
Mình search nhiều trên Github repo của nhóm mà không tìm được api-token để request API. Admin có thể cấp cho mình 1 token để phát triển không ạ? Cảm ơn admin nhiều nhiều!

**Comment by anhhai680** [comment]
> Mình search nhiều trên Github repo của nhóm mà không tìm được api-token để request API. Admin có thể cấp cho mình 1 token để phát triển không ạ? Cảm ơn admin nhiều nhiều! Bạn có thể gửi qua email của mình qua: thuongle.it@gmail.com. 

Mình thấy có open api mà bạn @thuongleit , xem phần open api ở phần giới thiệu cuối trang chủ dự án xem thử thế nào bạn.

**Comment by thuongleit** [comment]
Mình đã request thử trên open api rồi. API yêu cầu có token để thực thi. 

![image](https://i.imgur.com/E8ZFjIq.png)

Theo PR #130 thì token được generated từ existing users. Mà hiện tại thì mình không biết làm sao để đăng ký user. Nhờ 2 anh @DungDA hoặc @dungpt3003 xem giúp với. Cảm ơn 2 anh Dũng!

**Comment by kc97ble** [comment]
Mình đã gắn nhãn `out of gen2 scope`.

Tham khảo: [Định hướng của Gen-2](https://docs.google.com/document/d/1InhG0Pd2Bpt-lY7rZAc7TyznlWhOxNCocRpVSFX720Y/edit?usp=sharing)
