### ISSUE TITLE
Tạo visualization từ dữ liệu của site qua API 

### ISSUE THREAD

**Issue by hailoc12** [Cuuhomientrung/cuuhomientrung#18]

**Comment by khiem111189** [comment]
Mình có tìm hiểu thì có một ví dụ để import dữ liệu lên bản đồ của Google Maps: https://developers.google.com/maps/documentation/javascript/importing_data

**Comment by mihnsen** [comment]
@hailoc12 cho ví dụ về cái visualization này nhé

**Comment by leophan** [comment]
Hiện tại cái này mình đang tiếp cận: Mapping địa chỉ tương đổi của người dân ra longitude and latitude.
Ví dụ: ` Sơn Thủy, Lệ Thủy, Quảng Bình` mình sẽ lookup ra được `17.223629, 106.710002` => Tạo Marker trên google map.

**Comment by freeloneman** [comment]
Đã có làm xong ở issue #33 nên discuss ở đó kẻo bị loãng thông tin nha mọi người
