### ISSUE TITLE
Có thêm tên miền ngắn hơn 

### ISSUE THREAD

**Issue by dvkndn** [Cuuhomientrung/cuuhomientrung#180]
Lúc nãy mình có truy cập và nhờ bạn bè truy cập trang web trên điện thoại thì nhận ra việc gõ đầy đủ tên miền khá dài, đặc biệt là trong tình huống không thoải mái (tụi mình khi đó đang ngồi trên xe, mình nghĩ đây là tình huống phổ biến).

Mình nghĩ những người quan tâm sẽ có bookmark, nhưng ở phía bọn mình cũng có thể (nếu không tốn quá nhiều chi phí) giúp bằng việc có những tên miền rút gọn :D ví dụ `cuuho.vn` hoặc `18006132.vn`

**Comment by dothanhlam97** [comment]
Tên miền này a @hailoc12 có mua không anh hay được donate :))

**Comment by kc97ble** [comment]
Tên miền càng ngắn thì càng tốn tiền. Nhưng mà em không nghĩ tiền là vấn đề đâu =)))

Tên miền ngắn, nếu có, chỉ nên là một tên miền redirect tới tên miền chính.
Giống như fb.com trỏ tới facebook.com.
Không biết mn có đồng ý như thế k ạ?

**Comment by dvkndn** [comment]
> Tên miền ngắn, nếu có, chỉ nên là một tên miền redirect tới tên miền chính.

@kc97ble em nói đúng ý anh muốn đề xuất đó :D 

> Tên miền càng ngắn thì càng tốn tiền. Nhưng mà em không nghĩ tiền là vấn đề đâu =)))

Tiền luôn là vấn đề chứ :)) nhưng nếu từ 3 ký tự trở lên thì anh nghĩ không bị special price như 2 với 1 ký tự.

Anh nghĩ mình nên đăng ký `chmt.vn` và `cuuho.vn` rồi redirect về trang chính

**Comment by kc97ble** [comment]
![image](https://user-images.githubusercontent.com/7184368/98019343-96b13900-1e3c-11eb-9116-eb9a99ca5b69.png)

Mua chmt.info nhé?

**Comment by baonq-me** [comment]
Em đang tiến hành mua domain `chmt.xyz` và sẽ redirect về trang `cuuhomientrung.info`.

**Comment by baonq-me** [comment]
Domain .xyz chỉ 29k/năm đầu tiên nên có thể mua thoải mái.

**Comment by xuanbao2008** [comment]
có nhất thiết tên miền phải .vn ko ạ? hay chỉ cần tên miền ngắn dễ nhớ là ok ạ?

**Comment by baonq-me** [comment]
Em đã setup xong chmt.xyz, nhờ anh @kc97ble verify giúp.

**Comment by kc97ble** [comment]
@baonq-me Cảm ơn bạn, mình sẽ báo cáo lên ban lãnh đạo.

**Comment by baonq-me** [comment]
Hiện em thấy trên tài liệu truyền thông đang để link đến trang chủ là https://bit.ly/cuuho20. Khi dùng domain mới thì cũng cần cập nhật lại.

**Comment by baonq-me** [comment]
![image](https://user-images.githubusercontent.com/1851037/98130985-6d9cb100-1eed-11eb-8751-4236779720ad.png)

@kc97ble  Anh thấy tên này thế nào anh

**Comment by kc97ble** [comment]
@baonq-me Mình nghĩ `chmt.vn` là hợp lý nhất. Mục đích của tên miền ngắn gọn là để gõ nhanh, đồng thời, vẫn phải đảm bảo tính dễ nhớ. `cuuho.me` có thể bị hiểu nhầm thành `kuuho.com`.

Từ đầu, đến giờ, trong đầu mình chỉ băn khoăn giữa hai lựa chọn: `chmt.vn` và `chmt.info`. Cái đầu thì ngắn hơn, còn cái sau thì dễ nhớ hơn. Ở đây, mình thấy tính ngắn quan trọng hơn tính dễ nhớ, bởi vì chỉ những người dùng trang web này nhiều thì mới tìm đến tên miền ngắn.

**Comment by dvkndn** [comment]
sao @kc97ble lại nghĩ ".info" dễ nhớ hơn ".vn" nhỉ? Anh thì nghiêng về ".vn" tại nó có ý nghĩa thuận hơn (chmt.vn = cứu hộ miền trung Việt Nam) :D

**Comment by baonq-me** [comment]
Em thấy chmt.vn là dễ nhớ nhất. Chỉ kẹt vụ ai đứng tên thôi.

**Comment by NguyenPhuongLinh1985** [comment]
Chị ko hiểu lắm về tech, nhưng thấy chmt.vn mang cảm giác tin tưởng hơn. Sorry c thấy xyz nó hơi... :D 
Thêm nữa, trên điện thoại chị chỉ cần gõ "c" là đã hiện lên luôn cuuhomientrung.info, click là được. Nên việc cảm thấy bị dài quá là do lần đầu truy cập thôi đúng ko?

**Comment by kc97ble** [comment]
Đóng. Cảm ơn chị @NguyenPhuongLinh1985
