### ISSUE TITLE
Bổ sung thông tin về tình trạng tại từng khu vực (độ sâu ngập / nước rút...) vào trang thống kê tỉnh/huyện/xã 

### ISSUE THREAD

**Issue by hailoc12** [Cuuhomientrung/cuuhomientrung#19]

**Comment by dothanhlam97** [comment]
@hailoc12 Cái này thêm vào phần status của Tỉnh, Huyện, Xã hả anh ?

**Comment by ChuNgoan1008** [comment]
Cái này thì cần thông tin gì ạ anh

**Comment by kc97ble** [comment]
@hailoc12 anh có thể trình bày rõ hơn được không ạ.

Theo em hiểu, mình cần thêm các mục sau đây:
- Độ sâu ngập: kiểu = số thực, đơn vị = mét
- Tốc độ dâng: kiểu = enum, giá trị = ???
- Các mối nguy hiểm khi tiếp cận: kiểu = string

Vì anh có kinh nghiệm thực tế, mong anh bổ sung để làm rõ tính năng nhé.

**Comment by hailoc12** [comment]
Cái issue này thuộc dạng nice to have thôi. Hiện tại cũng không cần vì trang của mình focus vào cứu nạn. Ngoài ra phần độ ngập sâu thì có các tool khác dùng viễn thám dự đoán được chính xác hơn. Anh close nhé
