### ISSUE TITLE
Cannot reading Error reading /code/project/webpack-stats.json

### ISSUE THREAD

**Issue by vuon9** [Cuuhomientrung/cuuhomientrung#193]
Hi, mình đang thử cài project trên máy, nhưng bị stuck vì lỗi này, mình không rành Python, mong sự giúp đỡ ạ!

```
Request Method: | GET
-- | --
http://localhost:8087/
3.1.2
OSError
Error reading /code/project/webpack-stats.json. Are you sure webpack has generated the file and the path is correct?
/usr/local/lib/python3.9/site-packages/webpack_loader/loader.py, line 28, in load_assets
/usr/local/bin/python3
3.9.0
['/code/project',  '/usr/local/lib/python39.zip',  '/usr/local/lib/python3.9',  '/usr/local/lib/python3.9/lib-dynload',  '/usr/local/lib/python3.9/site-packages']
Sat, 31 Oct 2020 21:27:02 +0700

```

![image](https://user-images.githubusercontent.com/3168632/97781835-855bf880-1bc0-11eb-85cc-69ecb50d18f2.png)

![image](https://user-images.githubusercontent.com/3168632/97781857-9efd4000-1bc0-11eb-95f0-d1a9f20cce75.png)

Thanks!

**Comment by kc97ble** [comment]
https://github.com/Cuuhomientrung/cuuhomientrung/pull/192

https://github.com/Cuuhomientrung/cuuhomientrung/pull/196

Vấn đề này đã được sửa sau khi merge hai PR này.

Bạn checkout lại nhánh origin/develop nhé.

**Comment by vuongggggg** [comment]
Mình thử thì có vẻ lỗi cũ đã không còn. Thanks!
Giờ gặp lỗi mới, mong bạn tiếp tục giúp mình với ạ!

![image](https://user-images.githubusercontent.com/3168632/97796459-e4635100-1c44-11eb-9829-bb16b7905c68.png)

**Comment by kc97ble** [comment]
Bạn thiếu bước chạy `npm run build`. Trong doc có ghi đó bạn.

**Comment by vuon9** [comment]
Thanks bạn nhiều, để mình thử lại.

**Comment by kc97ble** [comment]
Comment nếu cần thêm sự giúp đỡ nhé. Tạm thời mình sẽ đóng issue này lại.
