### ISSUE TITLE
Tối ưu banner ở homepage

### ISSUE THREAD

**Issue by mihnsen** [Cuuhomientrung/cuuhomientrung#194]
From @dvkndn ```Tối ưu hình ở trang chủ. Mình không chắc hình có được tối ưu chưa, nhưng cái rõ hơn là kích thước khá lớn. Nếu người dùng vào bằng điện thoại (mình nghĩ là phổ biến) thì kích thước này khá là dư thừa.```

--- 
cái này do bên nào đó design thì phải, phải nhờ @kc97ble  xem lại xem ai design rồi nhờ họ làm 1 version mobile nhỉ.

**Comment by dvkndn** [comment]
@kc97ble trong commit https://github.com/Cuuhomientrung/cuuhomientrung/commit/14bac8b2099436e6cb079ac23c15229138f78507 là em solve cái này rồi đúng k nhỉ?

**Comment by kc97ble** [comment]
Đóng.

Đã nén ảnh. Không cần nén thêm đâu ạ.
