### ISSUE TITLE
Remove loading ở homepage

### ISSUE THREAD

**Issue by mihnsen** [Cuuhomientrung/cuuhomientrung#195]
@DungDA có cách nào remove cái loading ở trang chủ này ko?
- Mình đoán là vì dùng webpack nên đang ném CSS vào trong file JS sau đó bung ra và ném lên header.
=> Solution theo mình là 
- Từ webpack build/output ra file CSS rồi include lên header
- Có reversion cho file CSS đó.
@dvkndn @kc97ble thảo luận thêm nha.

**Comment by DungDA** [comment]
@mihnsen mình có khắc phục vấn đến ném file css sau khi js của webpack load xong bằng cái `preloader` animation rồi đó. Tức là khi vào web người dùng sẽ có phần loading, đợi webpack nó chạy xong xuôi hết rồi thì tự động tắt cái preloader đi

**Comment by dvkndn** [comment]
@DungDA tức là vẫn còn cái loading hở anh? Anh thấy mình có nên bỏ cái loading đó luôn không?

Tại em thấy phần nội dung của mình là đã render server-side rồi, còn ở app chỉ load CSS với JS nên có thể không cần block user (bằng cái loader) trong khi CSS và JS load.

Hoặc đơn giản hơn là mình reference đến cái CSS và JS do webpack build từ trong layout.html template luôn được k nhỉ?

**Comment by xuanbao2008** [comment]
Đã fixed, mọi người review pr bên trên giúp mình nhé, ok thì chúng ta merge vào master

**Comment by phuongtnd91** [comment]
> Đã fixed, mọi người review pr bên trên giúp mình nhé, ok thì chúng ta merge vào master

P đã test trên local, check code và thấy không có vấn đề gì nhé :)
