### ISSUE TITLE
Yêu cầu sửa link trên trang chủ

### ISSUE THREAD

**Issue by kc97ble** [Cuuhomientrung/cuuhomientrung#197]
![image](https://user-images.githubusercontent.com/7184368/97785465-1d1d0f00-1be0-11eb-986f-c339251f50f8.png)

![image](https://user-images.githubusercontent.com/7184368/97785663-746faf00-1be1-11eb-8d37-ad21012ca243.png)

![image](https://user-images.githubusercontent.com/7184368/97785729-cadced80-1be1-11eb-8579-87bd95012a69.png)

![image](https://user-images.githubusercontent.com/7184368/97785845-83a32c80-1be2-11eb-9d2e-863746065f8c.png)

**Comment by dothanhlam97** [comment]
![image](https://user-images.githubusercontent.com/17758870/97789624-d4eaf600-1bb9-11eb-9194-b0d2785459e3.png)

"Thông tin trên site được kết nối tới Sở chỉ huy tiền phương phòng, chống lụt bão của Quân khu IV đặt tại Thừa Thiên Huế làm đầu vào cho công tác điều phối cứu hộ.
Các trường hợp cần cứu hộ khẩn cấp, xin gọi theo số hotline: 1800 6132 (miễn phí, 24/7) để đội cứu hộ tới ứng cứu."

Đang làm <p> 1 rem

**Comment by kc97ble** [comment]
@dothanhlam97 Đề cập issue trong phần mô tả PR nhé. Cái issue này được sửa xong hết rồi đúng không?

**Comment by kc97ble** [comment]
Đóng.

Đã hoàn thành.
