### ISSUE TITLE
Yêu cầu sửa trang hộ dân (2)

### ISSUE THREAD

**Issue by kc97ble** [Cuuhomientrung/cuuhomientrung#199]
Đây là một số đề xuất, không bắt buộc.

![image](https://user-images.githubusercontent.com/7184368/97786714-7ab55980-1be8-11eb-9945-03890fcb10da.png)

**Comment by dothanhlam97** [comment]
code production vẫn chưa update, cái merge mới nhất đã sort theo name rồi :D

**Comment by DungDA** [comment]
@dothanhlam97  anh build prod từ hôm cn rồi, em check lại xem

**Comment by kc97ble** [comment]
Đóng.

Số 1 đã xong.
Số 2 nên chờ https://github.com/Cuuhomientrung/cuuhomientrung/issues/208
Số 3 không quan trọng lắm.
