### ISSUE TITLE
Thêm POST methods cho API

### ISSUE THREAD

**Issue by author31** [Cuuhomientrung/cuuhomientrung#206]
Em thấy cái project này rất ý nghĩa, em muốn bổ sung thêm tính năng quét mã QR để có thể điền thông tin hộ dân nhanh cóng hơn. Em muốn viết 1 trang web có form đơn giản để các anh chị tình nguyện viên quét mã QR liên kết để trang web form điền và nộp ạ.

**Comment by kc97ble** [comment]
Chào bạn. Có phải issue này là một phần nhỏ của cái này https://github.com/Cuuhomientrung/cuuhomientrung/issues/208?
