### ISSUE TITLE
Cho phép gõ tên trong phần lọc tỉnh/huyện/xã

### ISSUE THREAD

**Issue by crazywolfxju** [Cuuhomientrung/cuuhomientrung#209]
Đối với trang hộ dân như hình:

![Screenshot (45)](https://user-images.githubusercontent.com/12232365/97934565-6d9b9480-1db9-11eb-93dd-e35ea2cb0bc3.png)

**Comment by dshongphuc** [comment]
Hi @crazywolfxju và mọi người,
Hiện tại mình dự định sử dụng plugin autoComplete này để implement tính năng cho phép gõ vào các field tỉnh / huyện / xã để lọc kết quả tìm kiếm : https://github.com/TarekRaafat/autoComplete.js 
Mình nghĩ plugin đó khá tốt vì nó là vanilla js chứ ko sử dụng jquery. Mình có kinh nghiệm với frontend nhưng lại chưa làm việc với python và django bao giờ, mình vừa install project và chạy ok trên local nhưng hiện tại các table tỉnh / huyện / xã đều đang trống vì thiếu database.
Mọi người có thể hướng dẫn mình cách dump data cho phần này được không ạ? Mình thử chạy file run_dump_database.sh nhưng có vẻ như đây chỉ là file dump các data mặc định của django chứ ko phải data chuẩn của project này.

Cám ơn anh chị em nhiều !

**Comment by mihnsen** [comment]
@kc97ble Trong cái phần em đang làm mới cho trang hộ dân có phần này ko?

**Comment by kc97ble** [comment]
Đóng.

Vui lòng thảo luận trong issue này https://github.com/Cuuhomientrung/cuuhomientrung/issues/209

**Comment by mihnsen** [comment]
Ref #208

**Comment by kc97ble** [comment]
Sorry mọi người, cái issue này không liên quan tới #208. Mình đã mở lại ạ.

**Comment by kc97ble** [comment]
Đóng. Đã hoàn thành. Cảm ơn @dshongphuc
