### ISSUE TITLE
Trong mục xem thông kê, Phần điểm nóng, tên các xã đang trùng lên nhau

### ISSUE THREAD

**Issue by crazywolfxju** [Cuuhomientrung/cuuhomientrung#210]
1)  Phần điểm nóng, tên các xã đang trùng lên nhau
Link đến trang: https://cuuhomientrung.info/dashboard
Đề xuất: xóa bỏ label vì khi kéo chuột qua các dấu tròn thì cũng có thông tin rồi
![25](https://user-images.githubusercontent.com/12232365/97960042-f6372680-1df3-11eb-9dce-cb1a0775c665.png)

**Comment by kc97ble** [comment]
Đóng. Bug tự biến mất khi có data.

![image](https://user-images.githubusercontent.com/7184368/99162130-12608f00-2735-11eb-99b6-8b3551cb17dc.png)
