### ISSUE TITLE
Phần trang Home, mục đăng ký tình nguyện viên nên link đến một google form

### ISSUE THREAD

**Issue by crazywolfxju** [Cuuhomientrung/cuuhomientrung#211]
Hiện tại: mục đăng ký tình nguyện viên đang link đến: https://www.facebook.com/cuuhomientrung.info/posts/115987070290919
Đề xuất: link đến một google form có thông tin giới thiệu và thông tin cần đăng ký.
![27](https://user-images.githubusercontent.com/12232365/97969483-76b15380-1e03-11eb-8413-f048770175a4.png)

**Comment by kc97ble** [comment]
Đóng.

Đội kỹ thuật (tech team) sẽ chỉ thực hiện thay đổi sau khi có yêu cầu chính thức từ đội điều phối, kèm theo một link tới một Google Form.
