### ISSUE TITLE
Cho phép tổng đài tự động gọi ra để xác nhận tình trạng người cần giúp đỡ

### ISSUE THREAD

**Issue by baonq-me** [Cuuhomientrung/cuuhomientrung#213]
Vấn đề:
Ở giai đoạn 1 cứu nạn, bước 3:
Tình nguyện viên gửi danh sách cứu hộ tới các tổ cứu hộ có thể tiếp cận hiện trường. Gọi thêm một lần nữa để check trạng thái chính xác của người dân.
 -> tốn nhân lực, có thể bỏ sót.

Giải pháp đề xuất:
Tổng đài tự động gọi ra và yêu cầu người nhận bấm phím trên điện thoại để xác nhận tình trạng, ví dụ bấm phím 1 để xác nhận đã được cứu, phím 2 nếu chưa được cứu, phím 3 nếu ..., phím 0 để gặp nhân viên hỗ trợ.
-> Bên nhận cuộc gọi không cần phải có tiền trong tài khoản, không yêu cầu smart phone, dễ sử dụng.

Bên cạnh đó, phần ticket cũng cần có độ ưu tiên để với những cuộc nào được xác nhận là chưa cứu thì cần tăng độ ưu tiên lên.

**Comment by dothanhlam97** [comment]
That's so cool.
Cho em thêm một ý nữa. Để feature có ý nghĩa, khi gọi xong thì mình nên note luôn vào note hoặc thêm 1 trường lịch sử để tnv biết đã có người gọi.

**Comment by kc97ble** [comment]
Mình thấy không thực tiễn lắm. Làm sao để người dân có thể tin tưởng vào một đoạn âm thanh được sinh tự động bởi một cái máy?

Mong nhận được góp ý từ anh @hailoc12 ạ.

**Comment by kc97ble** [comment]
Mình thấy tính năng khá thú vị, song mình e người dân sẽ cảm thấy không an tâm với giải pháp này.

**Comment by dothanhlam97** [comment]
Có 2 vấn đề mình cũng băn khoăn:
1. Mọi người khi được 1 số tổng đài gọi tới, và nghe mọi người k phải người thật nói chuyện -> sẽ không dám nghe tiếp vì sợ rút hết tiền dt, case này ở VN đã xảy ra quá nhiều.
2. Rất nhiều người k biết dùng bàn phím đt khi đang nghe đt (minh chứng sống là người thân ở nhà mình =)) )

**Comment by kc97ble** [comment]
Trong lúc nguy cấp, việc được nghe giọng nói của một người thật sẽ mang đến cảm giác an tâm hơn rất nhiều.

**Comment by baonq-me** [comment]
> Trong lúc nguy cấp, việc được nghe giọng nói của một người thật sẽ mang đến cảm giác an tâm hơn rất nhiều.

Mình có option bấm phím 0 để gặp nhân viên hỗ trợ đó bạn.

**Comment by baonq-me** [comment]
> Có 2 vấn đề mình cũng băn khoăn:
> 
> 1. Mọi người khi được 1 số tổng đài gọi tới, và nghe mọi người k phải người thật nói chuyện -> sẽ không dám nghe tiếp vì sợ rút hết tiền dt, case này ở VN đã xảy ra quá nhiều.
> 2. Rất nhiều người k biết dùng bàn phím đt khi đang nghe đt (minh chứng sống là người thân ở nhà mình =)) )

> Mình thấy không thực tiễn lắm. Làm sao để người dân có thể tin tưởng vào một đoạn âm thanh được sinh tự động bởi một cái máy?
> 
> Mong nhận được góp ý từ anh @hailoc12 ạ.

Lúc tình nguyện viên gọi điện xác nhận lần đầu tiên có thể báo trước về vấn đề này mà. Hơn nữa vấn đề mà giải pháp này giải quyết là không có đủ người để gọi vì vậy nếu có đủ người rồi thì tất nhiên là không cần làm thế này.

**Comment by phuongtnd91** [comment]
Mình nghĩ đây là một tính năng khá thiết thực trong lúc nguy cấp, vì không chắc sẽ có đủ nguồn lực để support mọi trường hợp thì ít nhất đây cũng là một giải pháp. (dù dĩ nhiên mình hiểu có người thât vẫn hơn)

**Comment by baonq-me** [comment]
Mình bổ sung thêm 1 đề xuất

> Bên cạnh đó, phần ticket cũng cần có độ ưu tiên để với những cuộc nào được xác nhận là chưa cứu thì cần tăng độ ưu tiên lên.

**Comment by kc97ble** [comment]
Duyệt.

Ừm, mình đồng ý với cách giải thích của bạn.

**Comment by kc97ble** [comment]
Có một số điều mình cần bạn làm rõ:
1. Khi nào thì tổng đài sẽ thực hiện cuộc gọi tự động?
2. Lời thoại của cuộc gọi?
3. Các lựa chọn mà người dùng có thể bấm.
4. Các hành động được thực hiện sau khi người dùng chọn một lựa chọn.
5. Tính năng này có làm ảnh hưởng tới bất cứ tính năng sẵn có nào k?

**Comment by baonq-me** [comment]
> Có một số điều mình cần bạn làm rõ:
> 
> 1. Khi nào thì tổng đài sẽ thực hiện cuộc gọi tự động?
> 2. Lời thoại của cuộc gọi?
> 3. Các lựa chọn mà người dùng có thể bấm.
> 4. Các hành động được thực hiện sau khi người dùng chọn một lựa chọn.
> 5. Tính năng này có làm ảnh hưởng tới bất cứ tính năng sẵn có nào k?

1. Khi tạo ticket, mình có thể tùy chọn có chạy auto call không và sau bao lâu thì chạy auto call. Việc cấu hình có thể thực hiện dễ dàng bằng cách nhập config trực tiếp vào phần mô tả. Ví dụ nếu nội dung ticket chứa chuỗi "[auto_call_1h]" thì có nghĩa là cứ sau 1h thì tiến hành gọi, "[no_auto_call]" thì có nghĩa là không chạy auto call.
2+3. "Chào bạn, đây là cuộc gọi tự động từ tổng đài cứu hộ miền trung 18006132. Bấm phím 1 để xác nhận đã an toàn. Bấm phím 2 nếu chưa được hỗ trợ. Bấm phím 0 để gặp nhân viên.". Sau khi bấm phím 1, 2 thì trả lời "Chúng tôi đã ghi nhận bạn [đã an toàn]/[chưa được hỗ trợ]".
4+5. Khi bấm phím 1, tổng đài sẽ gọi API cập nhật trạng thái của ticket thành "đã an toàn". Khi bấm phím 2, tổng đài sẽ gọi API nâng độ ưu tiên của ticket. Nếu sau 3 lần gọi thất bại thì cập nhật trạng thái ticket thành "không liên lạc được".

**Comment by dothanhlam97** [comment]
Cho mình thêm 1 góp ý nữa: Khi gọi xong thì mình nên note luôn vào note hoặc thêm 1 trường lịch sử để tnv biết đã có người gọi.

**Comment by kc97ble** [comment]
Cảm ơn bạn. Mình đã hiểu ý tưởng, song phần giải pháp hiện đang có một số vấn đề.

- Việc sử dụng chuỗi "[auto_call_1h]" tạo ra sự không rõ ràng, khó đoán. Giả sử hộ dân được tạo lúc 13:00 với chuỗi "[auto_call_1h]", sau đó, đến 13:30, hộ dân được cập nhật. Vậy thời gian gọi điện sẽ là 14:00 hay 14:30?
   - Giải pháp trước mắt: sử dụng format "[auto_call=YYYY-MM-DD hh:mm]", ví dụ: "[auto-call=2020-11-04 17:00]".
   - Giải pháp lâu dài (và cũng là cách làm chuẩn): chỉnh sửa model `HoDan`, thêm một trường là `scheduled_auto_calls`, lưu lại danh sách các cuộc gọi tự động.

**Comment by phuongtnd91** [comment]
Mình thấy giải pháp lâu dài của Kiên hợp lý nhưng giải pháp trước mắt thì mình hơi băn khoăn ở một số điểm sau:
1. Nếu sử dụng format "[auto_call=YYYY-MM-DD hh:mm]", nghĩa là chỉ auto-call vào thời điểm đó và một lần duy nhất hay thế nào? Hay là vẫn set interval từ cuộc gọi đầu tiên đó và gọi tối đa 3 lần?
2. Trong trường hợp edit ticket và thay đổi thời gian đó sau khi auto-call đã được thực hiện thì có trigger auto-call thời gian mới nữa không? 

Mình nghĩ có thể sử dụng theo cách của bạn Bảo, lấy mốc thời gian là lúc tạo (như trong ví dụ của Kiên là sẽ gọi vào 14:00).

**Comment by baonq-me** [comment]
> Cảm ơn bạn. Mình đã hiểu ý tưởng, song phần giải pháp hiện đang có một số vấn đề.
> 
> * Việc sử dụng chuỗi "[auto_call_1h]" tạo ra sự không rõ ràng, khó đoán. Giả sử hộ dân được tạo lúc 13:00 với chuỗi "[auto_call_1h]", sau đó, đến 13:30, hộ dân được cập nhật. Vậy thời gian gọi điện sẽ là 14:00 hay 14:30?
>   
>   * Giải pháp trước mắt: sử dụng format "[auto_call=YYYY-MM-DD hh:mm]", ví dụ: "[auto-call=2020-11-04 17:00]".
>   * Giải pháp lâu dài (và cũng là cách làm chuẩn): chỉnh sửa model `HoDan`, thêm một trường là `scheduled_auto_calls`, lưu lại danh sách các cuộc gọi tự động.

Thực ra em thấy nếu có field riêng thì sẽ tốt hơn. Tuy nhiên như em có nói đó là cách nhanh nhất, vì để có field riêng thì phải chờ người khác làm task thì mới có được, như vậy tiến độ task này sẽ bị phụ thuộc. Mình có thể làm tạm trước để release sớm nhất có thể. Sau đó khi nào có field riêng thì chỉ việc chuyển sang dùng.

**Comment by kc97ble** [comment]
> Mình thấy giải pháp lâu dài của Kiên hợp lý nhưng giải pháp trước mắt thì mình hơi băn khoăn ở một số điểm sau:
> 
> 1. Nếu sử dụng format "[auto_call=YYYY-MM-DD hh:mm]", nghĩa là chỉ auto-call vào thời điểm đó và một lần duy nhất hay thế nào? Hay là vẫn set interval từ cuộc gọi đầu tiên đó và gọi tối đa 3 lần?
> 2. Trong trường hợp edit ticket và thay đổi thời gian đó sau khi auto-call đã được thực hiện thì có trigger auto-call thời gian mới nữa không?
> 
> Mình nghĩ có thể sử dụng theo cách của bạn Bảo, lấy mốc thời gian là lúc tạo (như trong ví dụ của Kiên là sẽ gọi vào 14:00).

Với format "[auto_call=YYYY-MM-DD hh:mm]", cuộc gọi tự động sẽ chỉ được gọi đúng một lần.
Nếu cần gọi 3 lần, thì TNV cần phải viết cái dòng kia 3 lần với 3 mốc thời gian khác nhau.

Không nên cho quá nhiều logic vội (ví dụ như việc gọi nhắc lại). Ta nên [keep it simple, stupid](https://en.wikipedia.org/wiki/KISS_principle). Tính năng phải đơn giản thì mới tạo được sự tin cậy.

Trước khi thực hiện việc lên lịch cuộc gọi lặp lại, ta cần xem xem logic của tính năng này như thế nào. Cần có một cái flow-chart quy định rõ ràng logic của tính năng. Việc này có thể mất thời gian.

Về việc sử dụng thời gian tương đối ("1h" thay vì "2020-11-04 17:00"), sẽ có rất nhiều trường hợp biên. Giả sử hộ dân được tạo lúc 09:00. Sau đó, TNV kết nối hộ dân đó với một đội cứu trợ lúc 13:00. Tại thời điểm này, TNV muốn hẹn giờ cuộc gọi 1h sau đó. Như vậy, TNV đó sẽ phải tính khoảng thời gian từ lúc hộ dân được tạo (09:00) tới lúc cuộc gọi được thực hiện (14:00), sau đó nhập dòng "[auto_call_5h]". Mình thấy làm như vậy khá bất tiện, dễ gây nhầm lẫn, không tự nhiên.

**Comment by phuongtnd91** [comment]
> 
> Với format "[auto_call=YYYY-MM-DD hh:mm]", cuộc gọi tự động sẽ chỉ được gọi đúng một lần.
> Nếu cần gọi 3 lần, thì TNV cần phải viết cái dòng kia 3 lần với 3 mốc thời gian khác nhau.
> 
> Không nên cho quá nhiều logic vội (ví dụ như việc gọi nhắc lại). Ta nên [keep it simple, stupid](https://en.wikipedia.org/wiki/KISS_principle). Tính năng phải đơn giản thì mới tạo được sự tin cậy.
> 
> Trước khi thực hiện việc lên lịch cuộc gọi lặp lại, ta cần xem xem logic của tính năng này như thế nào. Cần có một cái flow-chart quy định rõ ràng logic của tính năng. Việc này có thể mất thời gian.
> 
> Về việc sử dụng thời gian tương đối ("1h" thay vì "2020-11-04 17:00"), sẽ có rất nhiều trường hợp biên. Giả sử hộ dân được tạo lúc 09:00. Sau đó, TNV kết nối hộ dân đó với một đội cứu trợ lúc 13:00. Tại thời điểm này, TNV muốn hẹn giờ cuộc gọi 1h sau đó. Như vậy, TNV đó sẽ phải tính khoảng thời gian từ lúc hộ dân được tạo (09:00) tới lúc cuộc gọi được thực hiện (14:00), sau đó nhập dòng "[auto_call_5h]". Mình thấy làm như vậy khá bất tiện, dễ gây nhầm lẫn, không tự nhiên.

Mình đồng ý với Kiên, giải pháp này sẽ dễ dàng và phù hợp với tình hình hiện tại. Mình đề xuất format theo kiểu: auto_call=[YYYY-MM-DD hh:mm, YYYY-MM-DD hh:mm, YYYY-MM-DD hh:mm], với key là auto_call và values có thể là 1 hay nhiều giá trị mốc thời gian. (thay vì viết câu kia thành nhiều lần)

Sau khi model Hodan được chuẩn hoá thì mình có thể phát triển tính năng auto-call scheduler (set thời gian trigger, set interval dạng optional....) và lưu nhật ký cuộc gọi...

**Comment by kdung** [comment]
Mình có vài ý kiến nhỏ nhỏ:

1. Flow lời thoại tự động: sau các hướng dẫn 0, 1, 2, nên có thêm 1 option để replay lại hướng dẫn, vd: "ấn phím * để nghe lại hướng dẫn lựa chọn"

2. Mình ko biết cách tổng đài tự động operate thế nào vì chưa làm bao giờ nên mấy câu dưới hỏi hơi ngu tẹo, mọi người thông cảm:
 - Nếu cấu hình thời gian gọi bằng chuỗi format trong ticket thì có nghĩa là bên tổng đài tự động (TDTD) sẽ phải liên tục scan các record & tách phần format ra hay có cách nào khác? Nếu simply scan như vậy có ảnh hưởng đến IO & SLA của database hay ko?
 - Mình thấy việc cấu hình theo interval (vd: 1h) cũng có pros là có thể cấu hình 1 lần cho tất cả các record chưa gọi (btw làm thế nào để biết record đó dc gọi hay chưa? scan & filter db again?). Trường hợp Kiên nêu ở trên thì có thể được giải quyết bằng cách đọc interval 1h tính từ last record update/last call được ko nhỉ?

Corner case: cá nhân mình cũng ko thích tổng đài tự động, mỗi khi gọi điện lên cho bank hay airlines chuyện tiền bạc trục trặc mà gặp tổng đài là đã thấy frustrated lắm rồi. Ko biết ở VN thế nào chứ bên này 100% nhấc máy nghe tiếng tổng đài gọi là tự động tắt luôn vì assume là scam, lỡ người ta cũng tắt như vậy cả 3 lần thì cái mark "Ko liên lạc được" do tổng đài mark nó có được phân biệt với "Ko liên lạc được" manually do người confirm hay ko?

**Comment by baonq-me** [comment]
Em gửi quy trình.

GIAI ĐOẠN 1 (CỨU NẠN): KHI TÌNH HÌNH NGUY CẤP
+ Bước 1: Tình nguyện viên nhập liệu những lời kêu cứu từ mạng xã hội hoặc tổng đài và dán nhãn "Cần xác minh".
+ Bước 2: Tình nguyện viên gọi xác minh thông tin gọi lại số điện thoại trong các tin kêu cứu. Dán nhãn “Không gọi được” (sau ít nhất 3 lần gọi), “Cứu hộ khẩn cấp”, "Cứu hộ không khẩn cấp", “Đã được cứu hộ”. Khi gọi xác nhận tình nguyện viên cần xin phép người nhận về việc tổng đài sẽ gọi tự động để xác nhận nếu người dân đã được cứu hộ cũng như thời điểm gọi xác nhận. Nếu cấu hình tự động gọi thì trên ticket sẽ hiển thị thời gian tự động gọi ra là "Tự động gọi ra xác nhận tình trạng vào lúc <hh:mm dd/mm>".
![image](https://user-images.githubusercontent.com/1851037/98133509-44c9eb00-1ef0-11eb-91c4-5232c9d6ad08.png)

+ Bước 3: Tình nguyện viên gửi danh sách cứu hộ tới các tổ cứu hộ có thể tiếp cận hiện trường và cập nhật trạng thái ticket thành "Đã gửi thông tin cho đội cứu hộ".
+ Bước 4: Tổng đài tự động gọi ra với các ticket đang ở trạng thái "Đã gửi thông tin cho đội cứu hộ", "Đã xác minh", "Gấp", "Không liên lạc được", "Xác nhận chưa được cứu hộ" theo cấu hình đã thực hiện ở bước 2. Nội dung câu chào như sau:
"Chào bạn, đây là cuộc gọi tự động từ tổng đài Cứu hộ Miền trung 18006132. Bấm phím 1 để xác nhận đã an toàn. Bấm phím 2 nếu bạn chưa được hỗ trợ. Bấm phím 0 để gặp nhân viên.". Nếu sau 5 giây không nhận được phím bấm thì tổng đài sẽ phát lại câu chào. Cuộc thoại sẽ kết thúc nếu sau 2 phút không nhận được phím bấm.
4.1 Sau khi người nhận bấm phím 1 thì trả lời "Bạn đã xác nhận mình an toàn. Xin cảm ơn." và cập nhật trạng thái ticket là "Xác nhận được cứu hộ lúc <hh:mm dd/mm>".
4.2 Sau khi người nhận bấm phím 2 thì trả lời "Đã ghi nhận bạn chưa được hỗ trợ. Chúng tôi sẽ gửi lại thông tin của bạn cho đội cứu hộ" và cập nhật trạng thái ticket là "Xác nhận chưa được cứu hộ lúc <hh:mm dd/mm>", thời gian tự động gọi lại được cộng thêm 6 giờ.
4.3 Sau khi người nhận bấm phím 0 thì cuộc gọi được chuyển qua tổng đài 18006132 để gặp nhân viên và cập nhật trạng thái ticket thành "Cần liên hệ thêm lúc <hh:mm dd/mm>". Khi đó nhân viên trực tổng đài cần chủ động cập nhật lại trạng thái ticket phù hợp với nội dung đã trao đổi với người cần hỗ trợ.
4.4 Nếu gọi không thành công thì trạng thái ticket chuyển sang:
4.4.1 "Không liên lạc được lúc <hh:mm dd/mm>" và thời gian tự động gọi lại được cộng thêm 1 giờ nếu trạng thái trước đó của ticket không phải là "Không liên lạc được".
4.4.2. "Xác nhận không liên lạc được lúc <hh:mm dd/mm>" nếu trạng thái trước đó của ticket là "Không liên lạc được".

Trường hợp đặc biệt:
- Người nhận cuộc gọi bấm phím 0 để gặp nhân viên tổng đài nhưng không gặp được ai: phía tổng đài cần có trigger để thông báo cho tình nguyện viên gọi lại.
- ...

**Comment by baonq-me** [comment]
![image](https://user-images.githubusercontent.com/1851037/98136212-4648e280-1ef3-11eb-9afe-9bf3262c6fe0.png)

**Comment by kc97ble** [comment]
Trước mắt, mình sẽ đề xuất phiên bản đơn giản lên ban điều hành nhé.

## Tóm tắt tính năng của version 1

Cho TNV hẹn giờ cuộc gọi tự động bằng cách thêm đoạn mã dưới dạng sau trong phần ghi chú:

```
[auto_call=YYYY-MM-DD hh:mm]
```

Ví dụ:

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut...

[auto_call=2020-11-05 16:00]

...aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum
```

Khi gặp mã này, hệ thống sẽ hẹn giờ một cuộc gọi tự động với ngày giờ như đã quy định. Xem mô tả cuộc gọi tự động bên dưới.

## Cuộc gọi tự động

Khi cuộc gọi tự động được kích hoạt, tổng đài sẽ gọi điện tới số máy của hộ dân với nội dung như sau:

"Chào bạn, đây là cuộc gọi tự động từ tổng đài cứu hộ miền trung 18006132. Bấm phím 1 để xác nhận đã an toàn. Bấm phím 2 nếu chưa được hỗ trợ. Bấm phím 0 để gặp nhân viên."

* Khi bấm phím 1, tổng đài trả lời "Chúng tôi đã ghi nhận bạn đã an toàn", sau đó, cập nhật trạng thái của hộ dân thành "Không cần hỗ trợ"
* Khi bấm phím 2, tổng đài trả lời "Chúng tôi đã ghi nhận bạn chưa được hỗ trợ"
* Khi bấm phím 0, tổng đài sẽ kết nối cuộc gọi tới TNV

@baonq-me kiểm tra thử xem như vậy đủ chưa ạ? Theo cảm giác của mình, ngay cả với version 1, cũng đã có khá nhiều corner case. Vậy nên đừng xông vào code vội nhé, chờ xem ban lãnh đạo duyệt đã.

**Comment by kc97ble** [comment]
Mình vừa bỏ nhãn `high priority` và thêm nhãn `need more info`.
Lý do: tính năng này cần được ban lãnh đạo duyệt trước khi ta có thể tiến hành.
Mình sẽ sớm cập nhật lại sau khi có phản hồi từ ban lãnh đạo.

**Comment by kc97ble** [comment]
@baonq-me Sau khi hỏi trên group chính, mình thấy ý kiến mọi người cũng trái chiều lắm. Một số ý kiến cho rằng cách này sẽ giúp tiết kiệm nhân lực, song một số khác hoài nghi về tính hiệu quả, sợ rằng tính năng này có thể làm rối hoạt động cứu trợ.

Ta có thể tiến hành thực hiện tính năng này, tuy nhiên, cần làm nhỏ trước, đánh giá hiệu quả, rồi mới làm rộng.

Mình đặt sẽ gắn nhãn `medium priority` bởi vì tính hiệu quả của tính năng này còn chưa rõ ràng. Các issue với nhãn `high priority` cần được ưu tiên hơn.

**Comment by kc97ble** [comment]
Mình đã gắn nhãn `out of gen2 scope`.

Tham khảo: [Định hướng của Gen-2](https://docs.google.com/document/d/1InhG0Pd2Bpt-lY7rZAc7TyznlWhOxNCocRpVSFX720Y/edit?usp=sharing)
