### ISSUE TITLE
Môi trường production, trang tình nguyện viên, vấn đề lỗi dữ liệu

### ISSUE THREAD

**Issue by crazywolfxju** [Cuuhomientrung/cuuhomientrung#214]
Có rất nhiều data bị như trong hình, hoặc để trống.
![29](https://user-images.githubusercontent.com/12232365/98038150-fb31bf80-1e5f-11eb-957c-a5cab9dd0759.png)

**Comment by kc97ble** [comment]
@crazywolfxju Cho mình hỏi tác động của vấn đề này tới hoạt động cứu hộ được không ạ? Vấn đề này gây cản trở công việc của mọi người như thế nào? Mình đang cân nhắc giữa việc gán nhẵn `high priority` và `highest priority`.

**Comment by DungDA** [comment]
Đã xoá xong dữ liệu spam trên production
