### ISSUE TITLE
[Production] Màn hình HOME, vấn đề giao diện

### ISSUE THREAD

**Issue by crazywolfxju** [Cuuhomientrung/cuuhomientrung#216]
![image](https://user-images.githubusercontent.com/12232365/98075829-6dca8b80-1eb0-11eb-95f1-e39be01bac4f.png)

**Comment by kc97ble** [comment]
Duyệt.

Cảm ơn @crazywolfxju  đã báo cáo.

**Comment by dshongphuc** [comment]
Để mình fix issue này nhé @kc97ble

**Comment by kc97ble** [comment]
Đã merge. Cảm ơn @dshongphuc
