### ISSUE TITLE
Chỉ cho phép nhập số trong phần điện thoại liên hệ của tình nguyện viên

### ISSUE THREAD

**Issue by baonq-me** [Cuuhomientrung/cuuhomientrung#217]
https://cuuhomientrung.info/admin/app/tinhnguyenvien/

![image](https://user-images.githubusercontent.com/1851037/98075857-b594e700-1e9f-11eb-8fee-bbc2e2db7de2.png)

Ngoài ra cũng cần xóa bớt các record rác.

**Comment by kc97ble** [comment]
Đóng.

Trùng với #214
