### ISSUE TITLE
Gộp 2 bước thu thập & nhập liệu thành 1 bước duy nhất

### ISSUE THREAD

**Issue by xuanbao2008** [Cuuhomientrung/cuuhomientrung#218]
Gộp 2 bước thu thập & nhập liệu thành 1 bước duy nhất.
làm thêm 1 trang input trên web luôn để TNV không nhập trên zalo group nữa, vậy mới rút ngắn được thời gian và công sức. Để làm điều này thì ở trang Thêm hộ dân cần có thêm tính năng Thêm nhanh, là 1 form để TNV có thể gõ / copy thông tin, hình ảnh vào, khi đó hệ thống sẽ tạo 1 record rồi push record này đi dạng push notification để team xác minh kiểm tra và nhập/edit thông tin chính xác đi kèm status để theo dõi được tình trạng xử lý. Có như vậy, chúng ta sẽ không bị bỏ sót data trên zalo khi tin zalo trôi quá nhanh và việc nhập liệu từ khâu thu thập cũng được chuẩn hóa tới mức tốt nhất. sau đấy team nhập liệu chỉ làm khâu kiểm tra và phân loại dữ liệu hậu cần (nếu có)

**Comment by kc97ble** [comment]
Ý tưởng rất hay. Hiện tại mình thấy bạn có đề xuất nhưng chưa được rõ ràng lắm đối với mình. Bạn có thể thêm một vài hình minh họa được không ạ? @xuanbao2008

**Comment by xuanbao2008** [comment]
ok, mình sẽ tạo 1 bản minh họa trước cuộc họp tối nay

**Comment by kc97ble** [comment]
@xuanbao2008 có thể vẽ một vài hình minh họa trong issue này để giải thích được không ạ? (hoặc paste cái link hôm nọ cũng được)

**Comment by kc97ble** [comment]
Mình đã gắn nhãn `out of gen2 scope`.

Tham khảo: [Định hướng của Gen-2](https://docs.google.com/document/d/1InhG0Pd2Bpt-lY7rZAc7TyznlWhOxNCocRpVSFX720Y/edit?usp=sharing)
