### ISSUE TITLE
[Production] [Trang thêm mới hộ dân] mục bản đồ, đề xuất ẩn viewbox hiển thị tọa độ và thêm button [Tìm vịtrí trên bản đồ] theo thông tin tỉnh, huyện, xã đã được điền trước đó.

### ISSUE THREAD

**Issue by crazywolfxju** [Cuuhomientrung/cuuhomientrung#221]
Trang thêm mới hộdân, link: https://cuuhomientrung.info/admin/app/hodan/add/
Cái view box như trong khung đỏ theo em được biết là ô hiển thịtọa độcủa điểm được đánh trên bản đồ. Em đang không biết về ý nghĩ của nó lắm đối với người dùng. 
Đềxuất:
1) Trong trường hợp người dùng không cần làm gì với nó thì mình ẩn nó đi
2) Thêm một button[Tìm vịtrí trên bản đồ]cho phép dùng thông tin xã, huyện, tỉnh đã được chọn ởcác mụcphía trên để tìm vịtrí trên bản đồ. Cụ thể là sau khi người dùng chọn thông tin ở các mục xã, tỉnh, huyện và click button[Tìm vị trí trên bản đồ] thì location icon sẽ được đặt ở vị trí cần tìm kiếm trên bản đồ.
Ý nghĩa: giúp tình nguyện viên dễ dàng xác định được vị trí của khu vực trên bản đồ.
![image](https://user-images.githubusercontent.com/12232365/98169003-d22c3000-1f2e-11eb-9fc4-5ffc7a44f5ca.png)

**Comment by DangHoangGeo** [comment]
Toạ độ đó không có ý nghĩa với người dùng nhưng cực kỳ quan trọng với mình.
1. Trường này được sinh tự động theo HoDanForm muốn chỉnh cũng khó.
2. Muốn tuỳ chỉnh theo ý mình thì phải tự customize lại  form nhập liệu. 

Thực tế là khi người dùng nhập địa chỉ ở bên trên thì mình nên gọi api lấy toạ độ và để đưa người dùng đến vị trí tương đối trên bản đồ. 
sau đó nếu họ hiểu biết khu vực đó tốt thì có thể tinh chỉnh để mình có vị trí chính xác hơn.
Dữ liệu hiện tại của mình trường này trống rất nhiều thì phải.

**Comment by kc97ble** [comment]
Cảm ơn @crazywolfxju đã tạo issue và @DangHoangGeo đã cung cấp thông tin.

Với thông tin như trên, mình nghĩ chưa cần quan tâm đến issue này vội.
Issue này sẽ tự động biến mất sau khi hoàn thành https://github.com/Cuuhomientrung/cuuhomientrung/issues/208

**Comment by kc97ble** [comment]
Sẽ đóng issue trong một vài ngày tới nếu không có bất cứ thảo luận nào thêm.
