### ISSUE TITLE
[Production] Trang hộ dân, hiển thị số lượng bản ghi thỏa mãn yêu cầu tìm kiếm

### ISSUE THREAD

**Issue by crazywolfxju** [Cuuhomientrung/cuuhomientrung#223]
Hiện trong trang này chưa hiển thị số lượng bản ghi thỏa mãn yêu cầu tìm kiếm cũng như tổng số lượng bản ghi hiện có
(Ví trí có thể như ở trong hình)
Việc hiển thị thông tin này có ý nghĩa giúp cho những người cứu hộ có thể nắm được thông tin về số lượng những người cần cứu hộ trong một vùng một khu vực nào đó họ đang quan tâm để có những phương án cứu hộ hoặc sắp xếp số lượng người cần cứu hộ phù hợp.

![1](https://user-images.githubusercontent.com/12232365/98171288-d3f7f280-1f32-11eb-82a4-bd8a1a6ad730.png)

**Comment by vucuong12** [comment]
Mình có thể lo phần này nhé

**Comment by crazywolfxju** [comment]
Chỉ cần hiển thị ở một vị trí nào đó dễ nhìn trong trang ạ. Trên hình là 2 vị trí đề xuất. Chỉ cần chọn một trong 2 nếu thấy hợp lý ạ.

**Comment by kc97ble** [comment]
Nên hiển thị dòng này ở bên dưới để tránh các vấn đề phát sinh khi người dùng chỉnh kích thước cửa sổ.

**Comment by vucuong12** [comment]
Done. 
![image](https://user-images.githubusercontent.com/11524188/98351222-53a9be00-2014-11eb-80d3-2262fdabb3a9.png)

**Comment by kc97ble** [comment]
Đóng. Đã hoàn thành. Cảm ơn @vucuong12
