### ISSUE TITLE
Thêm chức năng phân quyền 

### ISSUE THREAD

**Issue by phuongtnd91** [Cuuhomientrung/cuuhomientrung#226]
Hiện tại tất cả mọi người đều vào được trang admin, chưa có phân quyền.

Mình muốn làm rõ thêm về yêu cầu của chức năng này một chút:
1. Những chức năng nào cần quyền admin. 
2. Ngoài quyền admin thì có cần những quyền khác không? (ví dụ như quyền superuser để quản lý các tài khoản admin...)

**Comment by kc97ble** [comment]
Mình đã gắn nhãn `out of gen2 scope`.

Tham khảo: [Định hướng của Gen-2](https://docs.google.com/document/d/1InhG0Pd2Bpt-lY7rZAc7TyznlWhOxNCocRpVSFX720Y/edit?usp=sharing)

**Comment by kc97ble** [comment]
Cái này để cho Gen-3 làm thôi ạ =))))
