### ISSUE TITLE
[Community] Tạo kênh thông tin liên lạc chung cho anh em contributors

### ISSUE THREAD

**Issue by dangquangdon** [Cuuhomientrung/cuuhomientrung#234]
Không biết anh em có kênh chat chung nào để tất cả mọi người (contributors/developers của project này) có thể tham gia trao đổi thông tin, làm quen, kết bạn cũng như trao đổi kiến thức xung quanh project này ko nhỉ. 
**Suggestion**: Slack, Telegram, ...

**Comment by dshongphuc** [comment]
Được vậy thì hay quá, mình vote 1 phiếu cho Slack nha hehe :D

**Comment by baonq-me** [comment]
Hiện đang dùng https://cuuhomientrung.slack.com

**Comment by dangquangdon** [comment]
@baonq-me bạn cho xin cái link invitation đc ko?

**Comment by kc97ble** [comment]
https://join.slack.com/t/cuuhomientrung/shared_invite/zt-irc2ky4w-xfWiwtwLQWL4BlqYSfFgfg
