### ISSUE TITLE
[Production] Data corruption

### ISSUE THREAD

**Issue by dangquangdon** [Cuuhomientrung/cuuhomientrung#239]
Không biết data ở trên production đc nhập vào như nào, hay import từ đâu nhưng mình thấy có vẻ bị lỗi nhiều đấy. Ví dụ như trên trang hộ dân, mình tìm theo tên thành phố Hà Nội:

![image](https://user-images.githubusercontent.com/38534469/98449139-c52f5c80-2139-11eb-9c26-bc836bd59641.png)

Địa chỉ Huyện Xã có thể là đúng, nhưng không hiểu sao Tỉnh/Thành lại là Hà Nội? Mình tin là còn có nhiều trường hợp khác tương tự. Để đánh giá hết đc xem bao nhiêu đúng bao nhiêu sai và sửa chúng thì mình nghĩ phải export toàn bộ data ra rồi cross check với dữ liệu hành chính như Huyện nào thuộc Tỉnh nào ...

Trường hợp Xã - Huyện - Tỉnh thì có thể sửa lại cho đúng được, mình nghĩ bạn nào thành thạo pandas có thể làm đc. Còn việc dữ liệu Hộ Dân -> Địa chỉ Xã Huyệ Tỉnh có đúng ko thì cái này chắc không thể đánh giá đc.

**Comment by baonq-me** [comment]
Data này cũ rồi nên có thể cũng không còn quan trọng nữa đâu anh.
