### ISSUE TITLE
[Production] Thiếu thông tin huyện, xã của tỉnh Thừa Thiên Huế

### ISSUE THREAD

**Issue by kc97ble** [Cuuhomientrung/cuuhomientrung#244]
Hiện tại, tỉnh Thừa Thiên Huế mới chỉ có một huyện, còn thiếu thông tin của các xã, huyện khác.

![image](https://user-images.githubusercontent.com/7184368/98807936-5cf0bb80-2456-11eb-9133-c759970c1255.png)

Yêu cầu: Bổ sung các xã và huyện còn thiếu đối với tỉnh Thừa Thiên Huế

**Comment by xuanbao2008** [comment]
@dungpt3003 khi nào xong thì báo mình nhé, để mình deploy

**Comment by dungpt3003** [comment]
https://github.com/Cuuhomientrung/cuuhomientrung/pull/245
Nhờ anh @xuanbao2008 và @kc97ble check PR này nhé, chỉ cần migrate lên là được, migration này chỉ thêm dữ liệu vào db đã có sẵn, không thay đổi bất kì cấu trúc gì.

**Comment by kc97ble** [comment]
Đóng. Đã hoàn thành. Cảm ơn anh @dungpt3003 @xuanbao2008
