### ISSUE TITLE
[HIGH PRI] Bổ sung API lấy danh sách hộ cần cứu trợ với search (theo sdt, tên) và filter (tinh, huyen, xa, tình trạng, thời điểm cập nhật cuối)

### ISSUE THREAD

**Issue by hailoc12** [Cuuhomientrung/cuuhomientrung#27]
# Mô tả: 
Đã có API CRUD cho các model (như hình dưới), như chưa có API để tìm kiếm danh sách hộ cần cứu trợ theo sđt (để check trùng lặp thông tin) và API để lấy ra danh sách hộ theo một vài điều kiện lọc nhất định (theo tỉnh, huyện, xã, tình trạng, khoảng thời gian cập nhật tin) 

<img width="722" alt="image" src="https://user-images.githubusercontent.com/288295/96574414-9de32d80-12f9-11eb-8533-24e39956326a.png">

**Comment by dothanhlam97** [comment]
Mình không làm export excel mấy cái này được hả a @hailoc12

**Comment by duongcongtoai** [comment]
Mấy cái value filter là string luôn hay có giao diện bắt id attribute vậy anh @hailoc12

**Comment by duongcongtoai** [comment]
https://github.com/hailoc12/cuuhomientrung/pull/39
Todo: add tìm kiếm theo tên
