### ISSUE TITLE
[Topic] Build client cho Android

### ISSUE THREAD

**Issue by bc67da8d** [Cuuhomientrung/cuuhomientrung#30]
Luồng thảo luận cho dev android

**Comment by dothanhlam97** [comment]
Thank you Hà Mã!
Tí nữa bọn mình sẽ thảo luận với team PR về việc lên ý tưởng tiếp cho website và hỗ trợ trên các thiết bị di động. Mình sẽ update sau trong task này nhé.

**Comment by bc67da8d** [comment]
hi Hà Mã đã init v1.0 tại https://github.com/bc67da8d/com-hamatim-cuuhomientrung

**Comment by kc97ble** [comment]
@dothanhlam97 Có cập nhật gì không ạ?
@bc67da8d Có vẻ như trong thời gian qua, mọi người tập trung làm web quá mà bỏ quên cái issue này :'(

**Comment by bc67da8d** [comment]
> @dothanhlam97 Có cập nhật gì không ạ?
> @bc67da8d Có vẻ như trong thời gian qua, mọi người tập trung làm web quá mà bỏ quên cái issue này :'(
môt thời gian dài API không ổn định nên anh em mobile đều stop hết cả

**Comment by bc67da8d** [comment]
với lại phía web đã được anh em tối ưu rất tốt nên thiết nghĩ mobile không có cũng không ảnh hưởng nhiều

**Comment by kc97ble** [comment]
Vâng, dự án ở giai đoạn mới đầu nên có nhiều thay đổi quá. Các bên thứ ba thông cảm ạ.
