### ISSUE TITLE
[HIGH PRI] Tạo trang import dữ liệu danh sách cần cứu hộ từ file csv 

### ISSUE THREAD

**Issue by hailoc12** [Cuuhomientrung/cuuhomientrung#32]
# Vấn đề: 
Hiện tại có rất nhiều nhóm trong cộng đồng cũng đang thu thập dữ liệu danh sách cứu hộ, tuy nhiên lưu vào google sheet ở nhiều format khác nhau 

Ví dụ: https://docs.google.com/spreadsheets/d/1kh38R8qdC8doVXKS-xjZzE3CG5jgAVHQKmQmEJAaOnY/edit#gid=0

# Nhu cầu: 
Xây dựng một trang import danh sách trường hợp cần cứu hộ ở dạng csv vào hệ thống (thông qua Open API tại https://cuuhomientrung.info/api/, hoặc code thành một view mới trong django). Yêu cầu: 

- file CSV có cấu trúc được định nghĩa rõ ràng. Các bên muốn import dữ liệu vào phải tiền xử lý để quy về dạng chuẩn này 
- dữ liệu khi import vào cần kiểm tra xem có trùng lặp không (thông qua check sdt liên hệ)
- tự động gán các trường tỉnh, huyện, xã dựa trên việc parse dữ liệu text

**Comment by freeloneman** [comment]
Nên import từ file Excel để người  dùng  có thể tự import, trên web có 1 file Excel mẫu để người dùng download và copy dữ liệu vào rồi import

**Comment by freeloneman** [comment]
https://datatofish.com/read_excel/

**Comment by kc97ble** [comment]
Hiện tại, em không thể assign cho chính em được. 

```
Assignees
No one assigned
```

**Comment by kc97ble** [comment]
Đây là bản thiết kế:

![Frame 7](https://user-images.githubusercontent.com/7184368/96613150-3052f380-1331-11eb-9816-fe13eeaaae33.png)

Nếu có vấn đề gì, mong mọi người góp ý ạ.
Giờ em bắt đầu code.

**Comment by mihnsen** [comment]
@kc97ble nếu ko nhận ra được column theo đúng format của mình liệu mình có thể có một bước map column ở ngay phần xem trước đó không?
Kiểu 
```
Họ tên => Hộ dân
Số điện thoại => Điện thoại liên hệ
Xa => Xã
...
```
Để khác format vẫn có thể map được column rồi import?
Nếu mất thời gian thì cứ để sau nhé.

**Comment by kc97ble** [comment]
## Định nghĩa tính hợp lệ

1. Tiêu đề cột phải khớp so với bảng khi export, tức là
   - Phải chứa đủ các cột: 

   Tên hộ dân | Tình trạng | Vị trí | Tỉnh | Xã | Huyện | Sdt | Cứu hộ | Thời gian cuối cùng cập nhật | Ghi chú
   -- | -- | -- | -- | -- | -- | -- | -- | -- | --

   - Thứ tự các cột không quan trọng

2. Các cột `Tình trạng`, `Xã`, `Huyện`, `Tỉnh`, `Thời gian cuối cùng cập nhật` phải sử dụng giá trị cho phép

3. Sử dụng `Sdt` làm căn cứ để cảnh báo trường hợp dữ liệu bị lặp. (đây chỉ lả warning, vẫn cho phép người dùng tiếp tục)

**Comment by kc97ble** [comment]
> @kc97ble nếu ko nhận ra được column theo đúng format của mình liệu mình có thể có một bước map column ở ngay phần xem trước đó không?
> Kiểu
> 
> ```
> Họ tên => Hộ dân
> Số điện thoại => Điện thoại liên hệ
> Xa => Xã
> ...
> ```
> 
> Để khác format vẫn có thể map được column rồi import?
> Nếu mất thời gian thì cứ để sau nhé.

Cái đó chắc để hôm sau ạ.

**Comment by freeloneman** [comment]
Nên có file Excel mẫu để hạn chế khác biệt với database. Người dùng muốn import thì trước hết tải file mẫu về, copy dữ liệu từ file của họ vào đúng cột rồi upload lên.

**Comment by freeloneman** [comment]
Sau khi lưu vào database thì query xem nếu nghi ngờ bị trùng thì liệt kê ra để người dùng tự kiểm tra và sửa thông tin

**Comment by kc97ble** [comment]
vâng ạ

**Comment by dothanhlam97** [comment]
Deprecated
