### ISSUE TITLE
Tạo bản đồ trên site

### ISSUE THREAD

**Issue by freeloneman** [Cuuhomientrung/cuuhomientrung#33]
Cần có bản đồ để người dùng tự chấm vào vị trí, hệ thống sẽ lưu theo tọa độ của Google Map, khi đó đội cứu hộ gõ tọa độ vào Google Map sẽ ra chính xác vị trí của người gặp nạn.

**Comment by mihnsen** [comment]
@freeloneman cái này có liên quan gì đến #18 không vậy? Có thể giải thích thêm
- Người dùng tự chấm vào vị trí - người dùng là ai? chấm vào vị trí là tạo một cái marker trên bản đồ à?
- Đội cứu hộ gõ tọa độ là sao nhỉ? Làm sao biết tọa độ để gõ?

**Comment by freeloneman** [comment]
Mới xem cái #18 thì chắc cũng giống ý, vì tiêu đề #18 ghi chung chung nên lúc nãy mình chưa rõ là có dùng bản đồ không. Lúc thấy trùng thì bạn Lộc gom 2 issue này lại thành 1 nhé.
- Chấm vị trí tức là chấm vào kinh độ và vĩ độ trên bản đồ (tương thích với Google Map)
- Về người dùng: có thể là cả  2 đối tượng, nếu người bị nạn có thể truy cập web thì họ tự thêm thông tin và tự chấm vị trí, còn nếu không thì TNV gọi điện xác định và chấm vị trí.
- Khi thông tin của nạn nhân đã được lưu vào database theo tọa độ thì có thể cung cấp mã vị trí cho người di cứu hộ để họ có thể định vị trên Google Map.

(Tham khảo cách sau của 1 bạn mình thấy reply trên group)
Phuong Minh Nguyen
ĐỊNH VỊ CHÍNH XÁC NGƯỜI DÂN MẮC KẸT TRONG LŨ VỚI MÃ CỘNG GOOGLE
Những ngày gần đây, các bài post kêu gọi cứu hộ/ cứu trợ từ người dân hoặc người thân của những người mắc kẹt trong lũ lụt tại các tỉnh miền Trung được chia sẻ rất nhiều trên FB, đa phần bao gồm số điện thoại, tên thôn/xã mà không có địa chỉ cụ thể. Như vậy sẽ rất khó để các đội cứu hộ hoặc người muốn giúp đỡ có thể tiếp cận được.
Trong khi đó, Google Maps đã có sẵn tính năng định vị bằng Mã Cộng, dựa trên kinh độ và vĩ độ, rất ngắn gọn và dễ dàng chia sẻ. Người dùng có thể lấy mã cộng vị trí hiện tại hoặc 1 vị trí bất kỳ chỉ bằng vài bước đơn giản. Người dân ở các vùng này hoặc người thân của họ có thể tận dụng để chia sẻ vị trí chính xác hơn, rút ngắn thời gian tìm kiếm và cứu hộ. Khi nhập mã cộng vào Google tìm kiếm hoặc Google Maps, kết quả trả về sẽ là một địa điểm trên bản đồ để có thể dễ dàng xác định được vị trí cũng như lộ trình di chuyển.
Hãy học cách sử dụng mã cộng để chia sẻ vị trí và giúp đỡ người thân ở khu vực chịu ảnh hưởng chia sẻ vị trí của mình bằng mã cộng, hoặc chia sẻ thông tin để nhiều người có thể tận dụng lợi ích của tính năng này trong tình huống cấp thiết hiện tại.
1 - Mở trang web google.com/maps​ hoặc ứng dụng Google Maps.
2 - Tìm vị trí nơi bạn muốn lấy Mã cộng (hoặc vị trí hiện tại). Để thả Ghim ở đó, hãy chạm và giữ màn
hình.
3 - Chạm vào ghim màu đỏ, mã cộng sẽ xuất hiện trong bảng điều khiển "Ghim đã thả". Ví dụ: GHR6+CQ Quảng Điền, Thừa Thiên Huế. Nhấn vào biểu tượng Mã cộng để sao chép tự động, và chia sẻ mã.
4 - Khi nhập mã cộng vào Google tìm kiếm hoặc Google Maps, kết quả trả về sẽ là một địa điểm trên bản đồ để có thể dễ dàng xác định được vị trí cũng như lộ trình di chuyển.

**Comment by mihnsen** [comment]
Mới xem qua thì thấy tinhte có bài hướng dẫn lấy cái mã cộng này: https://tinhte.vn/thread/chia-se-ma-cong-google-maps-cho-anh-em-vung-lu-khong-co-dia-chi.3206291/

**Comment by freeloneman** [comment]
Vậy để làm nhanh thì chỉ cần lưu cái mã cộng này vào database tương ứng với thông tin của nạn nhân là được. Dev cần tạo công cụ để các bạn TNV làm việc này khi  kiểm tra thông tin người bị nạn.

**Comment by mihnsen** [comment]
@freeloneman vậy dev chỉ cần cung cấp một ô input để nhập thôi hay tận dụng luôn trường location? sau đó từ danh sách hộ dân dẫn ra google maps là được phải ko ạ?

**Comment by freeloneman** [comment]
Mình nghĩ thêm input ở trang này là được rồi
https://cuuhomientrung.info/app/hodan/add/
Trong trang list thì có thêm link để dẫn ra Google Map

**Comment by mihnsen** [comment]
@freeloneman em có cái PR #44 này để
- Add google plus code vào form, các bạn TNV có thể thêm trường này vào mỗi lần thêm mới hộ dân
- Có link đến google map trên danh sách các hộ dân.

**Comment by mihnsen** [comment]
@freeloneman sau khi nó được approve thì e nhờ bác hướng dẫn các bạn TNV nhập cái dạng thông tin này luôn ạ :)

**Comment by dothanhlam97** [comment]
Cảm ơn anh @mihnsen nhiều! Tính năng này rất hay!

**Comment by mihnsen** [comment]
new PR: https://github.com/Cuuhomientrung/cuuhomientrung/pull/67

**Comment by ChuNgoan1008** [comment]
anh ơi cho em cùng vào nhóm tạo bản đồ này với ạ em cảm ơn nha

**Comment by mihnsen** [comment]
@ChuNgoan1008 a ko ở trong nhóm đó, a làm cái issue dựa trên chat với a @freeloneman.
@freeloneman a add bạn @ChuNgoan1008 vào nhé.

**Comment by freeloneman** [comment]
> anh ơi cho em cùng vào nhóm tạo bản đồ này với ạ em cảm ơn nha

@ChuNgoan1008 hiện tại Task này chưa cần gấp nên chưa có team riêng, có góp ý gì thì bạn cứ thảo luận ở đây nhé. Mọi người đang ưu tiên thời gian cho các task [HI PRI].

**Comment by ChuNgoan1008** [comment]
vang ạ anh nhé

**Comment by kc97ble** [comment]
@dothanhlam97 issue này còn vấn đề gì nên chưa close à?

**Comment by kc97ble** [comment]
Issue này sẽ được đóng trong hôm nay nếu không có thêm bất cứ thảo luận nào.

**Comment by kc97ble** [comment]
Đóng. Đã được giải quyết.
