### ISSUE TITLE
[HIGH PRI][DJANGO] Paging Giới hạn 30 records 1 trang

### ISSUE THREAD

**Issue by dothanhlam97** [Cuuhomientrung/cuuhomientrung#45]
mình có thể để số lượng bản ghi là 30/page được không ạ? Hiện em thấy hình như là 100 records, kéo mãi mới thấy cái thanh kéo ngang ạ
Các API cần có phân trang, ưu tiên với những API lượng data lớn như Hộ dân, tình nguyện viên

**Comment by voasd** [comment]
Related to #40
