### ISSUE TITLE
[HIGH PRI][DJANGO FILTER] Thêm search xã theo tên

### ISSUE THREAD

**Issue by dothanhlam97** [Cuuhomientrung/cuuhomientrung#46]
https://cuuhomientrung.info/app/xa/
Hỗ trợ cho đội cứu trợ tìm nạn nhân theo xã:
2 solutions:
-  Thêm tìm kiếm theo tên xã để đội cứu trợ tìm kiếm cho nhanh.
-  sort theo số lượng hộ dân cần cứu
Hiện tại có hơn 100 xã. nhưng chỉ 20% xã là có người cần cứu. Nếu cứu hộ dùng điện thoại kéo sẽ rất lâu.

**Comment by dothanhlam97** [comment]
@DungDA  em check mãi mà vẫn chưa sort được :( ở trong XaAdmin. Anh xem được thì support để Cứu hộ dùng được page này mượt mà luôn nhé!

**Comment by duongcongtoai** [comment]
Bạn thử override cái get_queryset xem, như thg Hodan Admin á

**Comment by thuyvan-kieu** [comment]
[UPDATE]: 
- Vì các tình nguyện viên và đội cứu hộ làm việc chủ yếu ở cấp độ xã, cần làm cho bộ lọc xã dễ sử dụng nhất có thể
- Ở bộ lọc xã thêm ô "Tìm kiếm" ở đầu danh sách, tnv có thể type tên xã để lọc kết quả, ko cần kéo xuống tìm kiếm từng xã
- Nếu có thể, làm tương tự cho bộ lọc tỉnh và huyện

**Comment by duongcongtoai** [comment]
Mình tối 8h mới available, bạn nào có time có thể xử lý tiếp nhé

**Comment by duongcongtoai** [comment]
> [UPDATE]:
> 
> * Vì các tình nguyện viên và đội cứu hộ làm việc chủ yếu ở cấp độ xã, cần làm cho bộ lọc xã dễ sử dụng nhất có thể
> * Ở bộ lọc xã thêm ô "Tìm kiếm" ở đầu danh sách, tnv có thể type tên xã để lọc kết quả, ko cần kéo xuống tìm kiếm từng xã
> * Nếu có thể, làm tương tự cho bộ lọc tỉnh và huyện

Feature này đã có rồi chị nhỉ, do ko thấy reference 
![Screenshot from 2020-10-22 19-44-35](https://user-images.githubusercontent.com/35887761/96873477-2e0ea780-149f-11eb-8eb0-608463ed556f.png)
