### ISSUE TITLE
Trình tự các app trên left side menu chưa hợp lý

### ISSUE THREAD

**Issue by trailaptrinh** [Cuuhomientrung/cuuhomientrung#48]
Nên để các thông tin sắp xếp theo trình tự Quan trọng, thường dùng hoặc Bao quát lên trên. Ví dụ hiện tại có thể để là:
1-Hộ dân
2-Đội cứu hộ
3-Thống kê Tỉnh
4-TK Huyện
5-TK Xã

**Comment by dothanhlam97** [comment]
![Uploading Screenshot 2020-10-24 at 15.10.48.png…]()
