### ISSUE TITLE
Trang chủ nên hiển thị danh sách tình nguyện viên thay vì trang admin

### ISSUE THREAD

**Issue by dieudv** [Cuuhomientrung/cuuhomientrung#49]
Trang chủ nên hiển thị danh sách tình nguyện viên để người dân vào có thể bấm vào số điện thoại gọi được ngay chứ không phải vào mò một lúc giữa đống menu.
Cái này có thể dùng bootstrap datatable cho nhanh.
Còn trang admin thì ở url riêng.

**Comment by dothanhlam97** [comment]
Changed plan
