### ISSUE TITLE
Thêm App Đội Cứu Trợ/ Nhóm Thiện Nguyện để kết nối hệ thống

### ISSUE THREAD

**Issue by maigiadn** [Cuuhomientrung/cuuhomientrung#51]
Hiện tại trên mạng xã hội có nhiều Tổ chức thiện nguyện có hàng nhưng không kết nôi được đơn vị vẫn chuyển và ngược lại. 
Đề xuất thêm 1 app tương tự như ĐỘI CỨU HỘ có tên là **ĐỘI CỨU TRỢ**  để lưu trữ thông tin này.
### Có 2 loại Đội Cứu Trợ bao gồm:
- **Cứu trợ vật phẩm** (_Các nhóm thiện nguyện_)
- **Hỗ trợ Vận Chuyển** (_Các nhà xe, cano, tàu thuyền_)
Các thông tin trường dữ liệu của 2 loại Đội Cứu Trợ: 
### **1. Cứu trợ vật phẩm**
 - Số điện thoại (trưởng đoàn)
- Vị Trí Cứu trợ (Thôn, Xã, Huyện, Tĩnh)
- Thời gian cứu trợ
- Số lượng vật phẩm (2 tấn gạo, 100 áo phao....)
- Tình trạng thông tin: Chưa kết nối đơn vị vận chuyển - Đã kết nối đơn vị vận chuyển
### **2. Hỗ trợ Vận Chuyển** 
 - Số điện thoại 
- Khu vực hỗ trợ (Hà Nội, Đà Nẵng, Quảng Bình)
- Thời gian hỗ trợ

**Comment by nmp191194** [comment]
mình nghĩ có thể thêm 2 trường thông tin sau vào model đội Cứu hộ để phân biệt loại hình và tài nguyên mà các bạn cung cấp:
- Loại hình (Chọn: Cứu trợ vật phẩm hoặc Hỗ trợ Vận Chuyển)
- Ghi chú cung cấp (free text)

**Comment by freeloneman** [comment]
@maigiadn scope của project này là tập trung cứu nạn cứu hộ còn cứu trợ thì mở API cho các bên khác, hoặc fork về và tự build. Trong Slack có channel open_api_and_thirdparty nếu muốn thì bạn hãy join để kết nối nhé.
