### ISSUE TITLE
Button xóa đã bị xóa, cần thêm lại để xóa các trường hợp trùng lặp hoặc thay đổi

### ISSUE THREAD

**Issue by crazywolfxju** [Cuuhomientrung/cuuhomientrung#53]

**Comment by nmp191194** [comment]
trên local mình vẫn thấy có chức năng xoá:
![image](https://user-images.githubusercontent.com/24238707/96709801-c3da0200-13cd-11eb-8a59-921f2a0b6d15.png)

**Comment by dothanhlam97** [comment]
Hiện tại không phải tất cả user đều có quyền xoá. Chỉ có admin mới có quyền. Cái này do config trên prod để chặn việc xoá dữ liệu.
