### ISSUE TITLE
Direct tới site bản đồ của https://vietnamhometown.com/

### ISSUE THREAD

**Issue by dothanhlam97** [Cuuhomientrung/cuuhomientrung#57]
mình có thể thêm tính năng view map theo tỉnh thành rất nhanh bây giờ: 
Mình sẽ sử dụng luôn site của anh HUy Gờ https://vietnamhometown.com/
1. Bên a Huy: vietnamhometown sẽ sử dụng luôn data của bên mình để hiện thị 
2. Bên mình: Tạo thêm 1 cột như trên ảnh 1, khi nhấp vào view map, mình sẽ direct qua trang kia + filter sẵn tỉnh luôn 
-> Hỗ trợ tnv và đội cứu hộ: có thể view trên map vùng này nguy cấp
![image](https://user-images.githubusercontent.com/17758870/96713398-7000f600-1398-11eb-9a97-25d06c4d17f5.png)

Solution:

Thêm 1 function trong class HoDanCuuHoStatisticBase (tương tự như get_ho_dan_can_ung_cuu)

**Comment by leophan** [comment]
Hiện tại task chỉ hỗ trợ filter theo xã, phái bên @Huy chưa hỗ trợ theo Huyện và Tĩnh
Mặc định Huyện và Tĩnh sẽ đá về site: http://vietnamhometown.com/

**Comment by kc97ble** [comment]
Đóng. Đã hoàn thành trong #65
