### ISSUE TITLE
Bộ lọc giao diện Mobile, web nên hiển thị trên đầu trang

### ISSUE THREAD

**Issue by maigiadn** [Cuuhomientrung/cuuhomientrung#6]
Mục Danh sách Đội Cứu Hộ/ Bộ Lọc đang hiển thị bên phải (giao diện web) và bên dưới (giao diện mobile). Đề xuất hiển thị Bộ lọc ngay phần đầu trang để các bạn có thể dễ dàng tìm thông tin, số điện thoại các đội cứu hộ theo khu vực.

![bo loc doi cuu ho](https://user-images.githubusercontent.com/70925042/96533684-8041a400-12b8-11eb-905a-8c11343989bf.png)

**Comment by mihnsen** [comment]
@dothanhlam97 Cái PR này + mấy cái fix width của note nó bay đâu rồi nhỉ, đã được merge mà a ko thấy code trên master. Sáng nay mọi ng vừa report lại cái này.

**Comment by dothanhlam97** [comment]
@mihnsen  em nghĩ là lúc build quên file static 
@DungDA Du @hailoc12 loc anh check giúp em nhé

**Comment by mihnsen** [comment]
@dothanhlam97 anh ko nghĩ vậy, chắc lúc đầu mình merge code với push trên master nhiều nên bị lẫn đâu đó. Phải ngồi tìm lại.

**Comment by mihnsen** [comment]
new PR: https://github.com/Cuuhomientrung/cuuhomientrung/pull/68
@dothanhlam97
