### ISSUE TITLE
[FRONTEND] Điều chỉnh width của table

### ISSUE THREAD

**Issue by dothanhlam97** [Cuuhomientrung/cuuhomientrung#7]
Reprod: 
Vào bất cứ trang nào có table https://cuuhomientrung.info/app/hodan/?tinh=8&status=1
Hiện tại width của table chưa hơp lý lắm. Hy vọng sẽ điều chỉnh được
<img width="1243" alt="Screenshot 2020-10-20 at 04 50 53" src="https://user-images.githubusercontent.com/17758870/96538222-f54cb380-128f-11eb-922c-81e1643aa39d.png">

Mình có tìm được 1 solution nhưng chưa thử:
This answer is useful
0

admin.py:

class MyClassAdmin(admin.ModelAdmin):

    class Media:
        css = {
            'all': ('fancy.css')
        }
fancy.css:

.column-foo {
    width: 20px;
}
where "foo" is a field name.

Source: https://docs.djangoproject.com/en/3.0/topics/forms/media/

**Comment by mihnsen** [comment]
Đây nữa @dothanhlam97

**Comment by mihnsen** [comment]
@dothanhlam97 Với issue này anh nghĩ là do như này:
https://snipboard.io/j5Fh7f.jpg

Sau khi xem rõ hơn thì anh thấy hầu hết css mọi ng để ở `/static/admin/css/....` nhưng file này mình đang để ở trong `/app/static/css/..` 
Em có thể xem lại rồi tạo thêm 1 pull request khác cho cái này nhé?
