### ISSUE TITLE
Show các trường hợp khẩn cấp ngay khi vào page

### ISSUE THREAD

**Issue by thuyvan-kieu** [Cuuhomientrung/cuuhomientrung#70]
Khi vào trang cuuhomientrung.info, show các trường hợp với tình trạng "Cần ứng cứu gấp" để các đội cứu hộ nhìn thấy ngay các trường hợp khẩn cấp 
Trang hiện tại, move sang cuuhomientrung.info/admin

**Comment by DungDA** [comment]
Cho bạn nào định làm task này
Solution:
- Viết 1 trang template riêng (Không liên quan đến admin dashboard). Template giống như này: https://thongtincuutro.com/
- Sau đó move admin router ra 1 namespace riêng /admin

**Comment by dothanhlam97** [comment]
Deprecated
