### ISSUE TITLE
[HIGH PRI] Hiển thị ID của Hộ dân

### ISSUE THREAD

**Issue by dothanhlam97** [Cuuhomientrung/cuuhomientrung#71]
Thêm cột số stt để làm id
<img width="1337" alt="Screenshot 2020-10-21 at 17 36 14" src="https://user-images.githubusercontent.com/17758870/96750591-05fe4600-13c4-11eb-9b5c-8edd428de9a2.png">

Hỗ trợ filter ở bên phải theo ID

**Comment by DungDA** [comment]
Đã giải quyết trên nhánh https://github.com/Cuuhomientrung/cuuhomientrung/tree/develop
