### ISSUE TITLE
Thêm cột: số lượng người cần cứu

### ISSUE THREAD

**Issue by dothanhlam97** [Cuuhomientrung/cuuhomientrung#74]
Thêm ở trang hộ dân:
<img width="1226" alt="Screenshot 2020-10-21 at 17 55 20" src="https://user-images.githubusercontent.com/17758870/96752652-ab1a1e00-13c6-11eb-8041-b4e24c5281cb.png">

**Comment by DungDA** [comment]
Đã thêm ở nhánh `develop`
