### ISSUE TITLE
Phần [tin tức quan trọng], cột [LINK], hiện các link thông tin đang không click trực tiếp được

### ISSUE THREAD

**Issue by crazywolfxju** [Cuuhomientrung/cuuhomientrung#78]
Mong muốn là khi click vào link được cung cấp có thẻ mở được trang thâng thông tin luôn thay vì phải copy link đến trình duyệt

**Comment by dothanhlam97** [comment]
<img width="1222" alt="Screenshot 2020-10-25 at 05 04 53" src="https://user-images.githubusercontent.com/17758870/97099326-ab910e00-167f-11eb-9cf2-022e8fe05be2.png">
Gắn tag <aa href=""> cho cột link

**Comment by thaidn** [comment]
Nếu chưa ai làm thì tôi sẽ làm phần này nhé.
