### ISSUE TITLE
Trong mục thống kê Tỉnh/Huyện/xã thêm các mục như ứng cứu gấp, gặp nạn.

### ISSUE THREAD

**Issue by crazywolfxju** [Cuuhomientrung/cuuhomientrung#79]
Các cột này hiển thị số lượng các trường hợp cần ứng cứu/gặp nạn ở các Tỉnh/huyện/xã tương tứng

**Comment by dothanhlam97** [comment]
<img width="1603" alt="Screenshot 2020-10-25 at 05 03 35" src="https://user-images.githubusercontent.com/17758870/97099290-784e7f00-167f-11eb-807f-c672bd8de9f6.png">
Ở các trang thống kê đều đã có số hộ cần ứng cứu.
