### ISSUE TITLE
[FRONTEND] Width của bộ lọc quá bé

### ISSUE THREAD

**Issue by dothanhlam97** [Cuuhomientrung/cuuhomientrung#8]
<img width="1337" alt="Screenshot 2020-10-20 at 04 56 38" src="https://user-images.githubusercontent.com/17758870/96538583-c256ef80-1290-11eb-885a-e708d96f02b4.png">

**Comment by dothanhlam97** [comment]
Checking

**Comment by DarkStarGit** [comment]
Filter nên để lên div search và chuyển label thành placeholder của select

**Comment by mihnsen** [comment]
@dothanhlam97 Cái này là xong chưa em? Code merge rồi phỏng?

**Comment by dothanhlam97** [comment]
@DungDA  em đã làm cái merge cho cái này rồi mà bản build hình như chưa up file css lên hay sao á anh. Anh kiểm tra giúp em nhé. Thanks anh!

**Comment by mihnsen** [comment]
@dothanhlam97 có gì liên quan đến file location ko xem thêm cái comment này xem có giúp ích gì ko https://github.com/Cuuhomientrung/cuuhomientrung/issues/7#issuecomment-713703712
