### ISSUE TITLE
Danh sánh hành chính (tỉnh, huyện, xã) chưa đúng chuẩn

### ISSUE THREAD

**Issue by hoangvietanh** [Cuuhomientrung/cuuhomientrung#80]
Trang thêm hộ dân cần cứu trợ https://cuuhomientrung.info/app/hodan/add/

Hiện tại danh sách tỉnh chưa được lấy từ 1 bảng chuẩn nên >> tỉnh còn bị trùng nhau, hoặc lúc viết chữ hoa, lúc viết chữ thường

Khi chọn tỉnh xong thì list huyện ko hiện đủ các huyện của tỉnh đó. 

![photo_2020-10-22_13-55-16](https://user-images.githubusercontent.com/4601538/96835883-621da480-146e-11eb-9720-23b2aa2fff1a.jpg)

Giải pháp:
- Trong DB cần có đủ 3 table tỉnh, huyện, xã toàn quốc và link với nhau qua foreign key >> trên giao diện việc chọn tỉnh, huyện, xã sẽ được nested với nhau để sau khi chọn 1 tỉnh thì các list huyện, xã sẽ được thu hẹp lại

**Comment by dungpt3003** [comment]
Mình nhận task này nhé, sẽ update lại database theo list trong file này:
[DVHC.xlsx](https://github.com/Cuuhomientrung/cuuhomientrung/files/5428918/DVHC.xlsx)

**Comment by dothanhlam97** [comment]
Xong chưa @dungpt3003 ơi. Rồi thì close task giúp mình nhé.

**Comment by dungpt3003** [comment]
@dothanhlam97 check Slack nhé.
