### ISSUE TITLE
[FRONT END][CSS] Fix staging - Đổi màu background

### ISSUE THREAD

**Issue by dothanhlam97** [Cuuhomientrung/cuuhomientrung#82]
Hôm qua team vừa lên một UI mới sử dụng một template hoàn toàn mới 
mọi người có thể vào link staging https://staging.cuuhomientrung.info/
Hiện tại thì màu xanh này hơi bị chói. Hy vọng sẽ quay trở lại được màu xanh nhã nhặn như site https://cuuhomientrung.info/

NOTE: Để vào được UI mới: Pull code branch develop (chỉ task này mới pull branch này nhé).

Bonus cho tấm hình :3 
<img width="1623" alt="Screenshot 2020-10-22 at 08 50 11" src="https://user-images.githubusercontent.com/17758870/96841343-99c32700-1443-11eb-8980-f821b4f723ab.png">

**Comment by mihnsen** [comment]
Cá nhân anh thấy cái gam màu tối trên staging là tương đối ổn.
![image](https://user-images.githubusercontent.com/9761138/96859641-edf1f980-148b-11eb-818b-b1aeec3e8cd1.png)

**Comment by dothanhlam97** [comment]
dạ Dũng mới đổi á anh
