### ISSUE TITLE
Mục search tỉnh/huyện đang không hoạt động

### ISSUE THREAD

**Issue by crazywolfxju** [Cuuhomientrung/cuuhomientrung#89]
![image](https://user-images.githubusercontent.com/12232365/96874575-3a9bfb80-14b1-11eb-95d4-f85967e826cf.png)

**Comment by duongcongtoai** [comment]
Detect sơ bộ : Production bị. Staging ko bị
Nhưng nếu mở tab của staging, để đó 1 thời gian sẽ bị lỗi field_id not found. => https://github.com/applegrew/django-select2/issues/103 setup cache backend cho server

**Comment by dothanhlam97** [comment]
@DungDA @hailoc12

**Comment by dothanhlam97** [comment]
can't reprod
