### ISSUE TITLE
Cần lọc bỏ các tỉnh ngoài đợt cứu trợ ra khỏi danh sách: chỉ giữ lại 6 tỉnh miền Trung trên giao diện

### ISSUE THREAD

**Issue by hoangvietanh** [Cuuhomientrung/cuuhomientrung#96]
Hiện tại dữ liệu gồm rất nhiều tỉnh ngoài 6 tỉnh miền Trung, gây rối cho người xử dụng

![QvARYF6Pbu](https://user-images.githubusercontent.com/4601538/96942371-28e14500-14ff-11eb-879d-f9c03dbe1b43.jpg)

**Comment by freeloneman** [comment]
Ah đúng, việc này cũng cần làm nhanh để tạo thuận lợi cho TNV. Bạn nhận task này luôn được không (chỉ lọc trên giao diện select chứ đừng xóa trong db vì ảnh hưởng đến hệ thống).

**Comment by freeloneman** [comment]
Mình xem lại thì thấy hình bạn chụp là chức năng thống kê theo tỉnh. List các tỉnh là do chính yêu cầu của TNV đưa ra, nên dùng chức năng Tìm kiếm cũng ổn mà bạn?

**Comment by dothanhlam97** [comment]
Mình nghĩ task này chính xác phải nằm ở Cái Filter trong hộ dân và ứng cứu 
<img width="1601" alt="Screenshot 2020-10-24 at 14 41 44" src="https://user-images.githubusercontent.com/17758870/97083319-0c303480-1607-11eb-90b0-a9f9fd8013e2.png">

@hoangvietanh confirm giúp mình nhé.

**Comment by dothanhlam97** [comment]
Mình không giới hạn chỗ này nhé. Bởi vì:
1. Trang thống kê đã fix để chỉ hiện những tỉnh có số hộ cần ứng cứu
2. Chỗ filter tỉnh huyện xã cũng đã có autocomplete
3. Hệ thống của mình đóng gói để chạy trên toàn quốc
