### ISSUE TITLE
Thêm chức năng export danh sách ra Excel

### ISSUE THREAD

**Issue by hoangvietanh** [Cuuhomientrung/cuuhomientrung#97]
Nên có thêm chức năng Export ra Excel cho tất cả các bảng. Excel là định dạng thông dụng và sẽ cần dùng rất nhiều cho in ấn, phân công làm việc nhóm.

**Comment by dothanhlam97** [comment]
@hoangvietanh  ở những trang nào anh ơi

**Comment by dothanhlam97** [comment]
Hiện tại có page Hộ Dân đã có export excel, các trang còn lại mong muốn sẽ được thêm tính năng export excel.

**Comment by kc97ble** [comment]
Duyệt. Em mong nhận được đánh giá về sự hữu ích của tính năng này để qua đó xác định độ ưu tiên. @hailoc12

**Comment by kc97ble** [comment]
Mình đã gắn nhãn `out of gen2 scope`.

Tham khảo: [Định hướng của Gen-2](https://docs.google.com/document/d/1InhG0Pd2Bpt-lY7rZAc7TyznlWhOxNCocRpVSFX720Y/edit?usp=sharing)
