### ISSUE TITLE
Bảng hộ dân cần ứng cứu: thêm các trường liên quan đến geolocation

### ISSUE THREAD

**Issue by hoangvietanh** [Cuuhomientrung/cuuhomientrung#99]
Bổ sung trường Pluscode để thêm Pluscode từ Google (do tình nguyện viên tra cứu google, kiểm tra và lấy Pluscode)
Thêm trường geometry để lưu chuỗi lat/long: sinh ra từ Pluscode ở trên

Các trường này sẽ dùng để hiển thị vị trí hộ cần cứu trợ lên bản đồ

**Comment by DungDA** [comment]
@hoangvietanh  hiện tại dùng qua cái mapbox để lấy địa điểm không ổn hả bạn

**Comment by freeloneman** [comment]
Trùng với issue #33 . Hiện tại đã có mã có thể paste vào Google Map.
![Uploading image.png…]()
